### PR TITLE
[develop] Add Sonarqube stage to the Jenkinsfile for PLATFORM-926

### PR DESCRIPTION
**Pull request by MichaelLueken**
## DESCRIPTION OF CHANGES: 
The EPIC Platform team is tasked with adding a `Sonarqube` gate to the SRW App's Jenkins pipeline.  @ankimball has added the `Sonarqube` pipeline into Jenkins, and requested that the `Sonarqube` stage be added to the `Jenkinsfile` in the SRW App's GitHub repository.  This work is adding the `Sonarqube` stage to the `.cicd/Jenkinsfile`.

Additionally, a fix has been made to allow the `Functional Workflow Task Tests` stage to successfully run on Hera GNU (30 minute wall time isn't enough for the the community test to finish using GNU compiled executables).

### Type of change
- [x] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
This is an update to the Jenkinsfile only.  There is no need to test this on any platform except for Jenkins.
- [x] Jenkins

## DEPENDENCIES:

None

## DOCUMENTATION:

None

## ISSUE:

[PLATFORM-926](https://jira.epic.oarcloud.noaa.gov/browse/PLATFORM-926)

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] My changes do not require updates to the documentation (explain).
This is an update to the Jenkinsfile only.  No documentation changes are required.
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

## CONTRIBUTORS (optional): 
@ankimball for providing the Sonarqube stage modifications.

### CODE REVIEW

**Comment by MichaelLueken** [comment]
All tests successfully passed, with the exception of `custom_ESGgrid_Central_Asia_3km`:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Central_Asia_3km                                    DEAD                   5.95
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200          COMPLETE               6.48
get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2  COMPLETE             763.07
get_from_HPSS_ics_HRRR_lbcs_RAP                                    COMPLETE              14.21
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2        COMPLETE               6.51
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot     COMPLETE              13.18
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_RAP                 COMPLETE              10.31
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2        COMPLETE               6.75
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2         COMPLETE             234.58
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16           COMPLETE             304.77
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR            COMPLETE             325.30
pregen_grid_orog_sfc_climo                                         COMPLETE               7.81
----------------------------------------------------------------------------------------------------
Total                                                              DEAD                1698.92
```
A rerun of the test successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Central_Asia_3km                                    COMPLETE              29.64
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              29.64
```
Currently testing a fix for the occasional issues encountered with the `Functional Workflow Task Tests`.  Once a fix that works on Hera GNU, Hera Intel, Orion, and Hercules is found, the change will be pushed and this PR will be opened.

**Comment by MichaelLueken** [comment]
An update was added to allow the `Functional Workflow Task Tests` to run and pass successfully on Hera GNU.  The Jenkins tests were run on Hera GNU and Hercules (previous modifications to correct this behavior caused issues on Hercules) and all tests passed.  While submitting the tests on these two machines, tests were also submitted on Jet, which had to be aborted both time.

Hera GNU:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Peru_12km                                           COMPLETE              29.21
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200         COMPLETE              15.39
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS                             COMPLETE              19.92
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR             COMPLETE              55.96
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta      COMPLETE              34.48
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0              COMPLETE              23.11
long_fcst                                                          COMPLETE              76.48
MET_verification_only_vx                                           COMPLETE               0.39
MET_ensemble_verification_only_vx_time_lag                         COMPLETE               8.36
nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16      COMPLETE              66.42
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             329.72
```
Hercules:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
custom_GFDLgrid__GFDLgrid_USE_NUM_CELLS_IN_FILENAMES_eq_FALSE      COMPLETE               9.43
grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16      COMPLETE              12.31
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta      COMPLETE              31.23
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              19.07
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR             COMPLETE              25.68
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP              COMPLETE              57.79
grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16   COMPLETE              15.45
grid_RRFS_NA_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP                 COMPLETE              66.83
grid_SUBCONUS_Ind_3km_ics_NAM_lbcs_NAM_suite_GFS_v16               COMPLETE              29.37
MET_verification_only_vx                                           COMPLETE               0.37
specify_EXTRN_MDL_SYSBASEDIR_ICS_LBCS                              COMPLETE               9.62
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             277.15
```
Opening this PR now.

**Review by RatkoVasic-NOAA — APPROVED** [review]
Looks good to me.

**Review by EdwardSnyder-NOAA — APPROVED** [review]
LGTM!

**Comment by MichaelLueken** [comment]
Thanks for the reviews, @RatkoVasic-NOAA and @EdwardSnyder-NOAA!  Merging this in now.

**Pull request merged**
