### PR TITLE
[develop] Bug fix for FV3_GFS_v17_p8 physics suite

### PR DESCRIPTION
**Pull request by EdwardSnyder-NOAA**
## DESCRIPTION OF CHANGES: 
A SRW App user noticed [an issue](https://github.com/ufs-community/ufs-srweather-app/issues/1004) with the `FV3_GFS_v17_p8` physics suite, that the surface temperatures were dropping unrealistically throughout the forecast. This PR addresses that issue by updating the `FV3_GFS_v17_p8` physics suite in the `parm/FV3.input.yml` file. 

This issue was discovered in the SRW App v2.2.0, but since the `FV3_GFS_v17_p8` physics suite is not [officially supported](https://ufs-srweather-app.readthedocs.io/en/release-public-v2.2.0/CustomizingTheWorkflow/ConfigWorkflow.html#ccpp-parameter) for the release, the change will only go into in the develop branch.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

I used a WE2E test to ensure the changes worked. The experiment can be found on Derecho here: /glade/work/esnyder/ufs-case-studies/expt_dirs/fan-update-3/grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot

_User Issue (before the PR) - sfc temp at fcst hour 6_
2mt_conus_f006

_PR Changes - sfc temp at fcst hour 6_
f2-2mt_conus_f006

- [ ] hera.intel
- [ ] orion.intel
- [ ] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [X] fundamental test suite on derecho:  /glade/work/esnyder/ufs-case-studies/expt_dirs
- [ ] comprehensive tests (specify *which* if a subset was used)

## DOCUMENTATION:

No documentation is required since the physics suites aren't thoroughly explained in the SRW App documentation.

## ISSUE: 

This PR addresses [Issue 1004](https://github.com/ufs-community/ufs-srweather-app/issues/1004).

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [X] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [X] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

## CONTRIBUTORS (optional): 

Thanks to @ulmononian, @ligiabernardet, Man Zhang, and Fanglin Yang for their help troubleshooting this problem!

### CODE REVIEW

**Comment by MichaelLueken** [comment]
The `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot` WE2E test was successfully ran on Hera:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              15.51
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              15.51
```

The cold bias noted in issue #1004 (and seen in the first image in the Tests Conducted section above) is no longer present following this update:

FV3_GFS_v17_p8

Approving this PR now.

**Review by MichaelLueken — APPROVED** [review]

**Comment by RatkoVasic-NOAA** [comment]
Test passed
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              15.12
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              15.12
```
2m temp ant hour 06:

2mtemp

Approving.

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by MichaelLueken** [comment]
@EdwardSnyder-NOAA -

As discussed at the meeting today, I will submit the Jenkins tests, but manually submit the fundamental tests on the platforms that have no allocations/fairshare.

**Review by mkavulich — APPROVED** [review]
Thanks for your work in fixing this issue!

**Comment by MichaelLueken** [comment]
The Jenkins tests have successfully passed on Derecho and Hercules.  One test failed for both the Gaea and Jet tests.

For Jet, the `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2` WE2E test failed in the `run_fcst` task.  Using rocotorewind/rocotoboot allowed the test to pass:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20240314184903                                           COMPLETE              19.36
custom_ESGgrid_20240314184904                                      COMPLETE              18.31
custom_ESGgrid_Great_Lakes_snow_8km_20240314184906                 COMPLETE              14.15
custom_GFDLgrid_20240314184908                                     COMPLETE               9.22
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018_202403  COMPLETE              10.95
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h_20  COMPLETE              56.37
get_from_HPSS_ics_RAP_lbcs_RAP_20240314184911                      COMPLETE              16.73
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20240314184913  COMPLETE             224.01
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              39.56
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               7.21
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_2024  COMPLETE             498.76
nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR_2024  COMPLETE              10.80
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             925.43
```
On Gaea, the `grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta` WE2E test also failed in the `run_fcst` task.  Again, the use of rocotorewind/rocotoboot allowed this test to successfully run:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20240314160319                                           COMPLETE              52.90
custom_ESGgrid_NewZealand_3km_20240314160327                       COMPLETE              58.75
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              37.65
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20240314160  COMPLETE              41.70
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024031416  COMPLETE              41.54
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE             374.67
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024031  COMPLETE              46.66
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             303.87
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              22.38
nco_ensemble_20240314160438                                        COMPLETE             139.08
nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thom  COMPLETE             351.10
2020_CAPE_20240314160506                                           COMPLETE              41.00
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1511.30
```
As expected, the Jenkins tests are sitting in queue on both Hera and Orion.  Thankfully, I was able to successfully run the WE2E coverage tests on Hera Intel using the Rocky 8 nodes:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Peru_12km_20240314181830                            COMPLETE              20.97
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200_2024031  COMPLETE               8.31
get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2  COMPLETE             790.93
get_from_HPSS_ics_HRRR_lbcs_RAP_20240314181834                     COMPLETE              16.09
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE              13.84
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              15.88
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_RAP_20240314181837  COMPLETE              12.03
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2_20240  COMPLETE               8.63
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_202403  COMPLETE             254.83
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_20240314  COMPLETE             319.18
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR_202403141  COMPLETE             337.68
pregen_grid_orog_sfc_climo_20240314181842                          COMPLETE               9.72
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1808.09
```
Given that the Orion `Functional Workflow Task Test` phase successfully passed (this test runs the default `community` WE2E test), as well as the default `nco` WE2E test in the coverage testing, I will go ahead and move forward with merging this work now.

**Pull request merged**
