### PR TITLE
Added functionality for MacOS X

### PR DESCRIPTION
**Pull request by natalie-perlin**
Added/updated functionality for MacOS, updated module list in srw_common

Files affected:
env/build_macos_gnu.env (new)
env/wflow_macos.env        (new)
env/srw_common                (updated)
env/build_macos_gccgfortran.env  (deleted)

### CODE REVIEW

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by mkavulich** [comment]
@natalie-perlin If srw-common is to be updated, this will need to be tested on all platforms. Can you please detail the tests that have been run? (preferrably using the PR template) I have applied the labels for automated testing on Hera and Jet.

**Comment by jkbk2004** [comment]
@natalie-perlin do we have any issue to use current srw_common for macos build/test? These hpc-stack updates should be coordinated across all platforms and all components. I recommend gradual upgrades. I am working on hpc-stack sync issue.

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by christopherwharrop-noaa** [comment]
FYI: Adding GSI and the RRFS Utilities to  SRW as described in #239 will also require updates to `srw_common`.  One of those required updates, `w3emc-2.9.2` is included in this PR.  So, if we don't update w3emc now, we'll still have to do it later.  If we can test/update it now, all the better.

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by jkbk2004** [comment]
> FYI: Adding GSI and the RRFS Utilities to SRW as described in #239 will also require updates to `srw_common`. One of those required updates, `w3emc-2.9.2` is included in this PR. So, if we don't update w3emc now, we'll still have to do it later. If we can test/update it now, all the better.

@christopherwharrop-noaa I will put a priority to come with a draft PR for the hpc-stack sync case.

**Comment by christopherwharrop-noaa** [comment]
@jkbk2004 - I do know that w3emc-2.9.2 is installed on Jet/Hera/Orion/Cheyenne (gnu and Intel)/WCOSS Dell.  I've already worked with hpc-stack folks to get that package installed on those platforms.  I'm not sure about the rest.

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/autoci/pr/916515726/20220422175019/ufs-srweather-app
+ fail 'Build jet intel FAILED'
+ echo -e '\nBuild jet intel FAILED\n'
Build failed
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/916515726/20220422175013/ufs-srweather-app
+ fail 'Build hera intel FAILED'
+ echo -e '\nBuild hera intel FAILED\n'
Build failed
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by jkbk2004** [comment]
> @jkbk2004 - I do know that w3emc-2.9.2 is installed on Jet/Hera/Orion/Cheyenne (gnu and Intel)/WCOSS Dell. I've already worked with hpc-stack folks to get that package installed on those platforms. I'm not sure about the rest.

@christopherwharrop-noaa I think the w3emc-2.9.2 is not going to affect ufs-wm/upp/ufs_utils level. Then we should be able to combine the w3emc-2.9.2 case into on-going PRs. I will check and bring the case to emc code managers.

**Comment by natalie-perlin** [comment]
The module ./env/srw_common  is reverted back to the current "develop" branch version. The env/build_mac_gnu.env does not load srw_common module, but instead loads individual HPC-stack modules built locally on the Mac that contain higher-versions of some packages. This avoids conflicts with builds for other platforms.

**Comment by jkbk2004** [comment]
> The module ./env/srw_common is reverted back to the current "develop" branch version. The env/build_mac_gnu.env does not load srw_common module, but instead loads individual HPC-stack modules built locally on the Mac that contain higher-versions of some packages. This avoids conflicts with builds for other platforms.

@natalie-perlin what about module load gftl-shared/v1.3.3?

**Comment by natalie-perlin** [comment]
@jkbk2004 - fixed the version of the gftl-shared in srw_common, updated the build_macos_gnu.env with all the modules loaded

**Review by jkbk2004 — APPROVED** [review]
@natalie-perlin Thanks!

**Comment by natalie-perlin** [comment]
This PR solves the issue #229 , and is supported by the SRW documentation updates #211, #240

**Comment by natalie-perlin** [comment]
After the recent updates and reversing the `srw_common` changes, putting them back to the current version on `develop`, there are no platforms that are affected by the current changes (except MacOS)

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
