### PR TITLE
[develop]: Update requests and certifi in requirements.txt

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
## DESCRIPTION OF CHANGES: 
The Dependabot PR #1101 identified the need to update the certifi version, but `requests` should also be updated from the current (yanked) version in the requirements file. 

### Type of change
- [X] This change requires a documentation update

## TESTS CONDUCTED: 
None required. Generated the requirements file locally with the proposed upgrade to `certifi` and then resolved warnings generated by the `requests` version. With these two updates, the `requirements.txt` file can be generated without warnings or errors. 

## DEPENDENCIES:
None.

## DOCUMENTATION:
All documentation. 

## ISSUE: 
Fixes issue identified in Dependabot PR #1101 

## CHECKLIST
- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas (N/A)
- [X] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain). (N/A)
- [X] My changes generate no new warnings
- [ ] New and existing tests pass with my changes (N/A)
- [ ] Any dependent changes have been merged and published (N/A)

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
Thanks for going through and updating the versions of both `certifi` and `requests`, @gspetro-NOAA!  Since you updated the "yanked" version of `requests` as well, I think I would prefer to get this PR in, then close PR #1101.

**Comment by natalie-perlin** [comment]
Could the ./ufs-srweather-app/doc/README be updates as well in this PR?

When sphinx, sphinx-rtd-theme have been installed (not going into the details of installations), the way to build the html documentaion requires the following:

$ cd ufs-srweather-app/doc
$ cp conf.py UsersGuide/.
$ make clean && sphinx-build -b html UsersGuide/ build

The above three lines would replace lines 23-24 in the current README
https://github.com/ufs-community/ufs-srweather-app/blob/develop/doc/README

**Review by natalie-perlin — APPROVED** [review]

**Comment by gspetro-NOAA** [comment]
@natalie-perlin I updated the doc README (and the regular README), but I used a two-line update rather than what you suggested. There should be no need to copy the `conf.py` file anywhere.

**Comment by MichaelLueken** [comment]
Thank you for updating the README files as well, @gspetro-NOAA!  Moving forward with merging this work now.

**Pull request merged**
