### PR TITLE
[develop] Update WM and UPP hashes

### PR DESCRIPTION
**Pull request by MichaelLueken**
## DESCRIPTION OF CHANGES: 
This PR brings the weather model hash to [26cb9e6](https://github.com/ufs-community/ufs-weather-model/commit/26cb9e60479958c4109a826c834333dcdd728a92) (May 2) and UPP to [5faac75](https://github.com/NOAA-EMC/UPP/commit/5faac752d9550d3570705358fa1eb3f5ac78a786) (April 9).

### Type of change
- [X] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
- [X] hera.intel
- [X] orion.intel
- [X] hercules.intel
- [X] derecho.intel
- [X] gaea.intel
- [X] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [X] fundamental test suite
- [X] comprehensive tests (specify *which* if a subset was used)

Fundamental tests were ran on all machines.  Comprehensive tests were ran on Gaea, Hera, Hercules, and Orion.

## DEPENDENCIES:
None

## DOCUMENTATION:
No documentation updates required

## ISSUE: 
None

## CHECKLIST
- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [X] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes

### CODE REVIEW

**Comment by RatkoVasic-NOAA** [comment]
With new tags, it compiled and single test on Hera passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024051020363  COMPLETE              20.63
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              20.63
```
Approved.

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by EdwardSnyder-NOAA** [comment]
Ran fundamental tests on AWS and they all passed. Approving.
```
Calculating core-hour usage and printing final summary
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE             150.83
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE              17.46
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              68.85
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024051  COMPLETE             286.17
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240513134  COMPLETE             110.64
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024051313465  COMPLETE             109.92
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             743.87
```

**Review by EdwardSnyder-NOAA — APPROVED** [review]

**Comment by MichaelLueken** [comment]
Hi @BruceKropp-Raytheon -

I just pushed a modification for the `grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0` WE2E test configuration that should correct the failure that is happening on Hercules.  Specifically, it is possible for the `run_fcst` job to either run the time steps in a second, or every 5 seconds.  If the node allows for 1 second time steps, then the `run_fcst` job will successfully pass in 1 hour.  However, if the node is running 5 second time steps, then the `run_fcst` job won't complete in 1 hour, leading to a failure due to exceeding walltime.  Increasing the walltime from 1 hour to 2 hours allows the `run_fcst` job to pass regardless of the node that is used on Hercules.

**Comment by BruceKropp-Raytheon** [comment]
Very nice @MichaelLueken ! 
I wonder if this is also the case for Orion and Jet, as these occasionally timeout before completing the single test.

**Comment by MichaelLueken** [comment]
@BruceKropp-Raytheon -

I believe that it is very similar to the occasional issues on Orion.

Looking at the failure on Jet from last night's test (before maintenance began), the `run_fcst` job successfully ran to completion.  There was a failure in verification.  The node that the failed job landed on was bad and the job hung until the walltime was hit, at which time it failed.

**Comment by MichaelLueken** [comment]
All Jenkins tests have successfully passed.  Moving forward with merging this work now.

**Pull request merged**
