### PR TITLE
[develop] fix CI scripts to save logfile names that Jenkinsfile needs for pwcloud platform builds

### PR DESCRIPTION
**Pull request by BruceKropp-Raytheon**
## DESCRIPTION OF CHANGES: 
Make sure the log file names match what jenkisnfile needs, specifically for PW cloud platforms, Azure, AWS, GCP

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
1. Run CI pipeline on Tier1 HPC to verify.
2. Run on PW cloud platforms to verify PASS of build stage with build log being properly uploaded to S3. 

- [x] hera.intel
- [x] orion.intel
- [x] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [x] derecho.intel
- [x] gaea.intel
- [ ] gaeac5.intel
- [x] jet.intel
- [ ] wcoss2.intel
- [x] NOAA Cloud (indicate which platform)
- [x] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
latest

## DOCUMENTATION:
No change.

## ISSUE: 
Auto-builds on PW platforms have been disabled dues to various failures. This removes one barrier.

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

## LABELS (optional): 
A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [x] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by EdwardSnyder-NOAA — APPROVED** [review]
The changes here match the file names in the Jenkinsfile.

**Review by MichaelLueken — APPROVED** [review]
@BruceKropp-Raytheon - These modifications ensure that the log file name is identical to what is being expected in the Jenkinsfile.

The `.cicd/scripts/srw_build.sh` script was tested on Jet and the SRW App was successfully built, while the `.cicd/scripts/srw_test.sh` was set to run the fundamental tests on Jet and the tests successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE               9.27
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               8.02
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              15.70
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024052  COMPLETE              40.38
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240529125  COMPLETE              29.85
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024052912571  COMPLETE              20.10
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             123.32
```
Approving PR now.

**Comment by MichaelLueken** [comment]
The Jenkins tests have successfully passed on Derecho, Gaea, Hera Intel, and Hercules.  Retests are currently being conducted on Orion, Jet, and Hera GNU.

**Comment by MichaelLueken** [comment]
The Orion rerun has successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_ESGgrid_SF_1p1km_20240530122620                             COMPLETE             422.01
deactivate_tasks_20240530122621                                    COMPLETE               1.13
get_from_AWS_ics_GEFS_lbcs_GEFS_fmt_grib2_2022040400_ensemble_2me  COMPLETE            1887.82
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_  COMPLETE            1032.53
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20240  COMPLETE             389.00
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta_202405301  COMPLETE              21.07
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20240530122  COMPLETE             881.45
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_  COMPLETE              66.14
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_2  COMPLETE             739.22
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0_202405  COMPLETE              61.91
2020_CAD_20240530122631                                            COMPLETE              70.73
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            5573.01
```
The Hera GNU rerun has successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Central_Asia_3km_20240530185954                     COMPLETE              62.90
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200_202405  COMPLETE              11.08
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_20240530185955              COMPLETE              16.68
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024053018  COMPLETE              72.65
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_202  COMPLETE              25.56
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240530185  COMPLETE              32.26
long_fcst_20240530185958                                           COMPLETE             100.83
MET_verification_only_vx_20240530185959                            COMPLETE               0.26
MET_ensemble_verification_only_vx_time_lag_20240530190001          COMPLETE               9.51
2019_halloween_storm_20240530190004                                COMPLETE              79.83
2020_jan_cold_blast_20240530190004                                 COMPLETE              79.31
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             490.87
```
The Jet rerun has successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
community_20240530175206                                           COMPLETE              18.34
custom_ESGgrid_20240530175207                                      COMPLETE              25.97
custom_ESGgrid_Great_Lakes_snow_8km_20240530175208                 COMPLETE              20.70
custom_GFDLgrid_20240530175210                                     COMPLETE              11.01
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018_202405  COMPLETE               9.22
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h_20  COMPLETE              87.59
get_from_HPSS_ics_RAP_lbcs_RAP_20240530175212                      COMPLETE              16.43
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20240530175213  COMPLETE             611.05
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              64.10
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               7.82
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_2024  COMPLETE             927.23
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1799.46
```
Moving forward with merging this work now.

**Pull request merged**
