### PR TITLE
[develop] Change Jenkins test to build with "all" target.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 

Extends the Jenkins build so that RRFS components may be added to coverage tests.

Also adds the first test to the Jet coverage suite. I'm choosing jet here since I'm doing most of my manual testing and development on Hera, it should help diversify the platforms GSL is most interested in.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

I ran the tests/build.sh script manually on hera. It passed.  I also ran the process_obs test against that build and it passed.

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@christinaholtNOAA These changes look good to me!

Your branch was cloned on Jet and the `.cicd/scripts/srw_build.sh` and `.cicd/scripts/srw_test.sh` scripts were ran to build the SRW App using the all option and then run the coverage tests, including the `process_obs` test.  The tests successfully passed.  Approving these changes now.

**Comment by christinaholtNOAA** [comment]
Can anyone else review this one? It's pretty straightforward and has been here for 2 weeks with only one review.

**Review by christopherwharrop-noaa — APPROVED** [review]
Looks good to me.  I don't see any issues.  Thanks for adding this.

**Comment by MichaelLueken** [comment]
The Jenkins tests were manually submitted on Orion and all successfully passed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
deactivate_tasks                                                   COMPLETE               1.42
get_from_AWS_ics_GEFS_lbcs_GEFS_fmt_grib2_2022040400_ensemble_2me  COMPLETE             751.52
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta   COMPLETE             252.07
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot        COMPLETE             140.51
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta            COMPLETE              14.00
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp  COMPLETE               9.98
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR              COMPLETE             374.94
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16   COMPLETE              27.69
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16    COMPLETE             297.97
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0         COMPLETE              13.25
nco                                                                COMPLETE               7.87
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1891.22
```

Awaiting the rest of the tests to successfully pass before moving forward with merging this work.

**Comment by MichaelLueken** [comment]
The automated Jenkins tests passed on Cheyenne and Hera Intel.  The `get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS` WE2E test on Hera GNU failed.  A resubmission of the failed task allowed it to pass:

```
[Michael.Lueken@hfe09 get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS]$ rocotostat -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10 | more
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202306270000               make_grid                    46519562           SUCCEEDED                   0         1           9.0
202306270000               make_orog                    46519593           SUCCEEDED                   0         1          56.0
202306270000          make_sfc_climo                    46519813           SUCCEEDED                   0         1          73.0
202306270000           get_extrn_ics                    46520077           SUCCEEDED                   0         1         720.0
202306270000          get_extrn_lbcs                    46520315           SUCCEEDED                   0         1          18.0
202306270000         make_ics_mem000                    46520397           SUCCEEDED                   0         1         668.0
202306270000        make_lbcs_mem000                    46520398           SUCCEEDED                   0         1        1234.0
202306270000         run_fcst_mem000                    46521546           SUCCEEDED                   0         1        1459.0
202306270000    run_post_mem000_f000                    46522249           SUCCEEDED                   0         1          13.0
202306270000    run_post_mem000_f001                    46522250           SUCCEEDED                   0         1          14.0
202306270000    run_post_mem000_f002                    46522251           SUCCEEDED                   0         1          14.0
202306270000    run_post_mem000_f003                    46522252           SUCCEEDED                   0         1          14.0
202306270000    run_post_mem000_f004                    46522253           SUCCEEDED                   0         1          13.0
202306270000    run_post_mem000_f005                    46522254           SUCCEEDED                   0         1          14.0
202306270000    run_post_mem000_f006                    46522255           SUCCEEDED                   0         1          13.0
```

The Jet tests failed.  This is likely due to the emergency downtime to roll back the Slurm version.  I will need to resubmit the Jet tests once the machine is brought back.

**Comment by MichaelLueken** [comment]
The rerun of the Jenkins tests on Jet once the Slurm update was complete successfully passed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
community                                                          COMPLETE              17.66
custom_ESGgrid                                                     COMPLETE              15.14
custom_GFDLgrid                                                    COMPLETE              11.05
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018         COMPLETE               9.41
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h     COMPLETE              47.68
get_from_HPSS_ics_RAP_lbcs_RAP                                     COMPLETE              15.41
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR                 COMPLETE             213.87
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot     COMPLETE              39.25
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2        COMPLETE               8.15
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta       COMPLETE             477.19
nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR       COMPLETE              10.92
process_obs                                                        COMPLETE               0.26
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             865.99
```

Merging this PR now.

**Pull request merged**
