### PR TITLE
[develop] Allow WE2E run script to set location of staged forecast files for verification

### LINKED ISSUE #597: Stage forecast data from the SRW App on Hera for running vx WE2E tests without running a forecast
## Description

 
On Hera, post-processed output files from the SRW App need to be staged in order to run the WE2E test `MET_verification_only_vx`.  This test uses staged forecast files (in grib2 format) along with staged obs to run deterministic verification.

The necessary observation files are already in the "authoritative" (is that the right adjective?) directory that stages data for testing the `develop` branch, which is at:
```
/scratch2/BMC/det/UFS_SRW_App/develop
```
The observations are in the subdirectory `obs_data`, but there are no staged **forecast** data from the SRW App.  (Note that there is staged external model data in the subdirectory `input_model_data`, but that data is from **external** models (FV3GFS, GSMGFS, RAP, HRRR, and NAM), not from the SRW App itself.)

## Solution

Currently, the staged files are in the personal directory
```
/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/DTC_ensemble_task/staged/fcst_det/2019061500/postprd
```
(Note that for now, the only date that's needed is `2019061500`.)  I propose to create a subdirectory under `/scratch2/BMC/det/UFS_SRW_App/develop` named `SRW_App_data` in which to place any output needed from the SRW App.  Under there, create the subdirectory `fcst_det` to contain deterministic forecast output from the SRW App (later, another subdirectory at this level named `fcst_ens` will be needed to hold staged ensemble output from the SRW).  To match the same naming convention as from an actual forecast with the SRW, the grib2 files will be placed in the subdirectory `2019061500/postprd` under `fcst_det`. 
 So the full path to the staged files will be:
```
/scratch2/BMC/det/UFS_SRW_App/develop/SRW_App_data/fcst_det/2019061500/postprd
```
Once this or a similar directory structure is agreed on in this issue, the test configuration file `config.MET_verification_only_vx.yaml` will have to be modified to point to the new staging location and a new PR opened to make this change.

In addition, it might be helpful to rename the subdirectory `input_model_data` that contains external model data to something like `extrn_model_data` so that it is clear that it contains only external model data, not data from the SRW itself.

## Requirements**

The WE2E test `MET_verification_only_vx` needs to succeed using the new staging locations.

## Acceptance Criteria (Definition of Done)

The WE2E test `MET_verification_only_vx` needs to succeed using the new staging locations.

## Alternative Solutions (optional)

Other layouts for the SRW staging directory are possible.  Please propose alternatives below.

### PR DESCRIPTION
**Pull request by gsketefian**
## DESCRIPTION OF CHANGES: 

This PR allows the SRW App to run the WE2E test that performs deterministic verification using staged forecast files (`MET_verification_only_vx`) using files in the authoritative location on a given platform (instead of in a user's directory).  This is done by:
1) Specifying the location of the staged forecast files in the machine file (for this PR, it is specified only for Hera) via the new variable `TEST_VX_FCST_INPUT_BASEDIR`.
2) Modifying `run_WE2E_tests.py` so that it correctly sets the variable containing this location (`VX_FCST_INPUT_BASEDIR`).  Depending on the experiment configuration, `VX_FCST_INPUT_BASEDIR` may be set using the value in the test configuration file, the machine file, or the default experiment configuration file.
3) Modifying the configuration file for the WE2E test `MET_verification_only_vx` so that it does not specify a user directory for `VX_FCST_INPUT_BASEDIR` (as well as for `CCPA_OBS_DIR`, `MRMS_OBS_DIR`, and `NDAS_OBS_DIR`).

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

The following fundamental tests were run on Hera with Intel.  All were successful.
- `MET_verification`
- `MET_verification_only_vx`
- `community_ensemble_2mems`
- `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp`
- `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot`
- `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2`
- `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16`
- `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR`
- `grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2`
- `grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR`
- `grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta`
- `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot`
- `MET_ensemble_verification`
- `community_ensemble_2mems_stoch`
- `pregen_grid_orog_sfc_climo`

## DOCUMENTATION:

No documentation changes needed.

## ISSUE: 

This is related to PR #597.  It makes it possible to use the staged files on Hera.

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by panll** [comment]
Looks good to me.

**Review by panll — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@gsketefian These changes look good to me!  Approving now.

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1235886940/20230215180517/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by gsketefian** [comment]
@MichaelLueken I noticed that after the last couple of PRs got merged, this PR was showing a conflict.  So I merged develop into my branch and retested all 14 fundamental tests listed in the PR message.  They all still pass.

**Pull request merged**
