### PR TITLE
[Release-v2.1.0] Various updates for release

### PR DESCRIPTION
**Pull request by mark-a-potts**
### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [X] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [X] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
This work is moving the UFS_SRW_App/develop contents into UFS_SRW_App/v2p1 for Gaea.  This is the first step in completing issue #452.  Approving this change.

**Review by danielabdi-noaa — APPROVED** [review]

**Comment by MichaelLueken** [comment]
@mark-a-potts Just wanting to check first, but are you hoping to modify the rest of the machine files with this PR, or is this ready to be committed?  Thanks!

**Comment by mark-a-potts** [comment]
No, it is not ready to be committed, yet. I am working through some of the errors that showed up in the comprehensive tests and trying to fix them where I can (mostly due to missing data or bad paths in machine files). I would also like to update all the "UFS_SRW_App/develop" instances to "UFS_SRW_App/v2p1" with this PR, but those changes won't work until the directories get created on all the machines. I'll be adding more commits to this over the weekend (maybe) and next Monday.

**Comment by danielabdi-noaa** [comment]
You may want to add a `run_vx.local` to Orion because I believe verification tasks will fail without it. I did the same for develop.

**Comment by EdwardSnyder-NOAA** [comment]
> You may want to add a `run_vx.local` to Orion because I believe verification tasks will fail without it. I did the same for develop.

Thanks @danielabdi-noaa, good catch! Just added it.

**Comment by mark-a-potts** [comment]
I have finished the comprehensive tests on Cheyenne (gnu) with the only failures being due to exceeding wall-clock times. The tests are now also passing on AWS and @EdwardSnyder-NOAA indicates they passed on Azure and GCP, so I am going to go ahead and merge this. I think it will be the final changes to code other than some possible tweaks for generic linux/mac installs from @natalie-perlin.

**Pull request merged**
