### PR TITLE
Fix quoting/escaping in Jenkinsfile

### PR DESCRIPTION
**Pull request by jessemcfarland**
## DESCRIPTION OF CHANGES: 
This PR properly quotes and escapes the line in the Jenkinsfile that removes large data sets from the experiment directory. Currently, the Jenkins pipeline will not execute due to this issue.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [x] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
Approving fix to quoting/escaping in Jenkinsfile.

**Review by MichaelLueken — CHANGES_REQUESTED** [review]
@jessemcfarland - The Jenkins CI is failing with this update:

```
WorkflowScript: 180: unexpected char: '\' @ line 180, column 111.
   xtype posix-extended -regex "^\.\/.*\/(o
                                 ^
```

Please see Jenkins CI [pipeline](https://jenkins-epic.woc.noaa.gov/blue/organizations/jenkins/ufs-srweather-app%2Fpipeline/detail/PR-403/2/pipeline).

**Comment by MichaelLueken** [comment]
@jessemcfarland @danielabdi-noaa Why is the Jenkins CI test [pipeline](https://jenkins-epic.woc.noaa.gov/blue/organizations/jenkins/ufs-srweather-app%2Fpipeline/detail/PR-403/3/pipeline/235) now failing for all of the builds?  There should be no difference between the successful runs from last night and this morning to the run currently running in Jenkins for PR #403.  Why was PR #378 able to set ${SRW_WE2E_COMPREHENSIVE_TESTS} to false, but PR #403 is unable to resolve this variable?

**Comment by danielabdi-noaa** [comment]
@MichaelLueken I believe it is because of a commit made in the morning to test out deleting only the large input/output files of the experiment directory so that we can keep the experiment directory longer and also reduce the upload size to S3. @jessemcfarland was in the process of testing this change and planning to run the fundamental tests on all platforms one more time. It is nothing to worry about because the worst is to undo those commits and everything will be back to normal.

**Comment by danielabdi-noaa** [comment]
Looks like Orion run finished successfully so approving.

**Review by danielabdi-noaa — APPROVED** [review]

**Comment by jessemcfarland** [comment]
I just wanted to ensure I fixed the SRW_WE2E_COMPREHENSIVE_TESTS variable issue with the Orion run. I'm running on all platforms to ensure the `find` command works properly. If this run passes, I think it's good to go.

**Comment by MichaelLueken** [comment]
> I just wanted to ensure I fixed the SRW_WE2E_COMPREHENSIVE_TESTS variable issue with the Orion run. I'm running on all platforms to ensure the `find` command works properly. If this run passes, I think it's good to go.

@jessemcfarland I'll keep my eye on the current Jenkins run.  Once it successfully completes, I will approve this PR and merge it.  Thanks!

**Review by MichaelLueken — APPROVED** [review]
All tests have passed in Jenkins, so I approve this update.

**Pull request merged**
