### PR TITLE
[develop] Fix `get_crontab_contents.py`

### LINKED ISSUE #1141: Calling `get_crontab_contents.py` as a script fails
## Expected behavior
`get_crontab_contents.py` should be callable as a python script.

## Current behavior
#1131 introduced a bug [on line 227](https://github.com/ufs-community/ufs-srweather-app/blob/develop/ush/get_crontab_contents.py#L227)that misnames the `ArgumentParser.parse_args` method to `_parse_args`; likely as a copy-paste error when renaming our internal method of the same name.

## Machines affected
All

## Steps To Reproduce
1. Clone and build the code (technically only the conda part of the build is needed for reproducing this bug)
2. Load the workflow module for your machine, activate conda environment
3. Run `python3 get_crontab_contents.py -m [your_platform]` and observe the error:

```
Traceback (most recent call last):
  File "/mnt/lfs5/BMC/gsd-fv3-test/kavulich/UFS/workdir/test_develop/2024-10-11/intel/ufs-srweather-app/ush/get_crontab_contents.py", line 237, in <module>
    args = _parse_args(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/lfs5/BMC/gsd-fv3-test/kavulich/UFS/workdir/test_develop/2024-10-11/intel/ufs-srweather-app/ush/get_crontab_contents.py", line 227, in _parse_args
    args = parser._parse_args(argv)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ArgumentParser' object has no attribute '_parse_args'. Did you mean: 'parse_args'?
```
## Detailed Description of Fix (optional)
Rename `parser._parse_args` back to the correct `parser.parse_args`

## Additional Information 
This problem was missed because the failure only occurs `get_crontab_contents.py` is called as a script for parsing arguments; imported calls to the function `get_crontab_contents` (which we have in both our unit test and in `generate_FV3LAM_workflow.py`) work just fine. The script is only called from `ush/launch_FV3LAM_wflow.sh`, and this is not covered in any of our automated or WE2E tests. We should consider adding tests for this script in the future.

### PR DESCRIPTION
**Pull request by mkavulich**
## DESCRIPTION OF CHANGES: 
Fix bug described in issue #1141: `get_crontab_contents.py` fails when run as a script

### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## TESTS CONDUCTED: 
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] hera.gnu
- [ ] hera.intel
- [ ] hercules.intel
- [x] jet.intel
  - Ran fundamental tests
  - Ran `get_crontab_contents.py` stand-alone before and after to confirm the fix.
- [ ] orion.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
None

## DOCUMENTATION:
None

## ISSUE: 
Fixes #1141

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@mkavulich -

Thanks for finding and correcting this issue.  I was able to confirm the same problem you noted in issue #1141 and that this update successfully corrects the current failure.

Approving PR now.

**Comment by MichaelLueken** [comment]
Currently, we are unable to run WE2E tests on Gaea and Derecho.  Coverage WE2E tests will be manually run on other machines for Gaea and Derecho.

**Comment by RatkoVasic-NOAA** [comment]
@MichaelLueken ufs-wm has just been updated to work on gaea-c5. Once we update SRW to this WM version, we should be able to run it on gaea.

**Comment by MichaelLueken** [comment]
> @MichaelLueken ufs-wm has just been updated to work on gaea-c5. Once we update SRW to this WM version, we should be able to run it on gaea.

Thanks for the update, @RatkoVasic-NOAA!

**Comment by mkavulich** [comment]
@MichaelLueken For the record, this portion of code is not used in any WE2E tests (which is why this problem wasn't noticed before) so running the full coverage tests is unnecessary. But I understand the need to be safe.

**Comment by MichaelLueken** [comment]
The Gaea coverage WE2E tests were successfully completed on Hercules:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20241018132111                                           COMPLETE              29.83
custom_ESGgrid_NewZealand_3km_20241018132111                       COMPLETE             116.74
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              52.54
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20241018132  COMPLETE              53.28
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024101813  COMPLETE              70.32
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE             756.70
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024101  COMPLETE              42.33
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             983.62
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              18.92
2020_CAPE_20241018132117                                           COMPLETE              48.70
2020_easter_storm_20241018132118                                   COMPLETE              67.19
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            2240.17
```

**Comment by MichaelLueken** [comment]
Derecho WE2E coverage tests were run on Orion:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
custom_ESGgrid_IndianOcean_6km_20241018151903                      COMPLETE              43.28
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE             102.22
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024101815190  COMPLETE              81.89
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR_20241018  COMPLETE              68.04
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              16.75
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024101815191  COMPLETE              47.70
pregen_grid_orog_sfc_climo_20241018151916                          COMPLETE              15.24
specify_template_filenames_20241018151919                          COMPLETE              15.62
2019_hurricane_barry_20241018151920                                COMPLETE              94.65
2019_memorial_day_heat_wave_20241018151922                         COMPLETE              85.86
2020_denver_radiation_inversion_20241018151923                     COMPLETE              99.73
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             670.98
```
and the Jet fundamental tests were run:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              11.68
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               9.95
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              32.28
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024101  COMPLETE              52.90
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241018190  COMPLETE              33.91
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024101819090  COMPLETE              53.28
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             194.00
```
All Jenkins WE2E coverage tests successfully passed on Hera GNU, Hera Intel, Hercules, and Orion.

As noted by  @mkavulich in https://github.com/ufs-community/ufs-srweather-app/pull/1142#issuecomment-2423069130, the modification in this PR aren't tested in the WE2E test suites, so no changes in the WE2E tests were expected.

Moving forward with merging this work now.

**Pull request merged**
