### PR TITLE
[develop] Adding SPFH to Metplus config file

### PR DESCRIPTION
**Pull request by panll**
## DESCRIPTION OF CHANGES: 

Adding specific humidity (SPFH) to Metplus config file for verification.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
None

## DOCUMENTATION:
N/A
## ISSUE: 

N/A
## CHECKLIST

- [ x] My code follows the style guidelines in the Contributor's Guide
- [ x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x ] My changes do not require updates to the documentation (explain).
   The change only relate to METPLUS configuration file.
- [ ] My changes generate no new warnings
- [x ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by JeffBeck-NOAA — COMMENTED** [review]
Hi @linlin-pan, thanks for adding specific humidity to the verification!  I only see 2-m SPFH at the moment, though.

**Comment by panll** [comment]
> Hi @linlin-pan, thanks for adding specific humidity to the verification! I only see 2-m SPFH at the moment, though.

The upper air part is already included in file PointStat_upper_air.conf. Thanks @JeffBeck-NOAA !

**Review by MichaelLueken — APPROVED** [review]
@panll I was able to clone your fork on Cheyenne and run the MET_verification test.  I was able to see the new SPFH Z2 entries in the `sfc` file.  I also saw several SPFH entries in the `upa` file.  Out of curiosity, was there a reason why SPFH was added to `upper_air`, but not `sfc`?

I will go ahead and approve this this PR, though it might be an idea to change the title of this PR from `Adding SPFH to Metplus config file` to `Adding SPFH to Metplus sfc config file`.

**Comment by panll** [comment]
> @panll I was able to clone your fork on Cheyenne and run the MET_verification test. I was able to see the new SPFH Z2 entries in the `sfc` file. I also saw several SPFH entries in the `upa` file. Out of curiosity, was there a reason why SPFH was added to `upper_air`, but not `sfc`?
> 
> I will go ahead and approve this this PR, though it might be an idea to change the title of this PR from `Adding SPFH to Metplus config file` to `Adding SPFH to Metplus sfc config file`.

Thanks! @MichaelLueken SPFH is missed in sfc file (PointStat_conus_sfc.conf), so this pull request adds SPFH to the sfc file  (PointStat_conus_sfc.conf) . In upper file (e.g., PointStat_upper_air.conf), SPFH has already existed. Thus no change is made to the upper file.

**Comment by JeffBeck-NOAA** [comment]
> > Hi @linlin-pan, thanks for adding specific humidity to the verification! I only see 2-m SPFH at the moment, though.
> 
> The upper air part is already included in file PointStat_upper_air.conf. Thanks @JeffBeck-NOAA !

Thank you, @linlin-pan!  Approving now.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
