### PR TITLE
[Release 2.1.0] Updated files to add WoFS to suites and tests

### PR DESCRIPTION
**Pull request by mark-a-potts**
### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [X] NOAA Cloud (AWS)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [X] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [X] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by natalie-perlin — APPROVED** [review]

**Comment by JeffBeck-NOAA** [comment]
@mark-a-potts, will this PR also be opened in the develop branch?  Thanks!

**Comment by mark-a-potts** [comment]
@JeffBeck-NOAA It will only work on develop once the WM has been updated there. Are we ready to update that on the develop branch?

**Comment by JeffBeck-NOAA** [comment]
@mark-a-potts, since it was merged as part of [this](https://github.com/ufs-community/ufs-weather-model/pull/1460) and [this](https://github.com/NOAA-EMC/fv3atm/pull/594) PR, it should be OK to add to our develop branch.

**Comment by mark-a-potts** [comment]
@JeffBeck-NOAA I meant that the hash to the WM in Externals.cfg needs to be updated in the develop branch of the ufs-srweather-app repo before the WoFS tests will work. We can update it and add in the tests to develop, if you think we are ready for that.

**Comment by JeffBeck-NOAA** [comment]
@mark-a-potts, oh, OK!  Yes, I think we can probably do that.  It's obviously not urgent, and the release is currently the focus, so we can certainly wait.

**Pull request merged**
