### PR TITLE
[develop] Add new ccpp physics suite 'FV3_GFS_v17_p8'

### LINKED ISSUE #573: CCPP physics suite 'FV3_GFS_v17_p8' does not work in UFS SRW App.
The CCPP physics suite `FV3_GFS_v17_p8`, which is included in the UFS weather model, does not work in the current UFS SRW App.

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
- Add the CCPP physics suite `FV3_GFS_v17_p8` to the UFS SRW App.
- Add a new WE2E test for the new suite.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- WE2E tests:
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8 (new)

- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 
Fixes issue mentioned in #573 

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## CONTRIBUTORS: 
@yangfanglin  @ChunxiZhang-NOAA

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]
Looks good to me.

**Review by MichaelLueken — APPROVED** [review]
@chan-hoo Thank you very much for making adding the `FV3_GFS_v17_p8` CCPP physics suite to the SRW App!  I just pushed a minor update, turning off the Hera Jenkins pipeline since EPIC can no longer run on Hera using the nems account and we haven't been given a new allocation as of this time.  I was able to test your newly added `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8` test on Jet without issue.  Approving these changes now.

**Comment by MichaelLueken** [comment]
@chan-hoo Before I move forward and merge this work, would you be able to merge the latest develop updates from today into your feature/ccpp_gfs_v17p8 branch?  Two of these modifications are to correct the failures in the unit tests and I'd like to make sure that, moving forward, no further failures are introduced.  Thanks!

**Comment by chan-hoo** [comment]
I found an issue on the conus 3km domain. please do not merge this PR yet.

**Comment by chan-hoo** [comment]
The issue on the 3km domain has been resolved.

**Review by BenjaminBlake-NOAA — APPROVED** [review]

**Pull request merged**
