### PR TITLE
[production/AQM.v7] AQM ecflow workflow EE2 review

### PR DESCRIPTION
**Pull request by lgannoaa**
This version is intended for EE2 review with AQM ecflow workflow located under ecf directory.

Current production/AQM.v7 using ${HOMEaqm}/ush/load_modules_run_task.sh to load main configuration file such as var_defns.sh. The generation of var_defns.sh and other configuration files are outside of scope from ecflow workflow. 
production/AQM.v7 needs to be modified to generate appropriate configuration files for production in $HOMEaqm/parm/config.

This version also contain the following changes:
  Bug fixes for SENDDBN and SENDDBN_NTC related application logic:  
    scripts/exregional_post_stat_pm25.sh
    scripts/exregional_post_stat_o3.sh
    scripts/exregional_bias_correction_pm25.sh
    scripts/exregional_bias_correction_o3.sh- Using production acceptable job name
    scripts/exregional_make_ics.sh- Exception handling in jobs attempt to access files.  scripts/exregional_run_post.sh
    scripts/exregional_nexus_emission.sh
    scripts/exregional_make_lbcs.sh  scripts/exregional_aqm_ics.sh
  Include aqm_ver in run.ver
  Using ${HOMEaqm}/parm/config as workflow configuration directory:
    ush/load_modules_run_task.sh

### CODE REVIEW

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, Can you test this PR with your NRT run? If it works, I'll merge this PR.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  Working on now and will let you know once the test is completed !

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  It seems that we are not able to test the package with rocoto workflow.  My jobs failed with the following error message 

/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.86/ush/load_modules_run_task.sh: line 10: /parm/config/var_defns.sh: No such file or directory

This means that  the rocoto workflow failed to read $HOMEaqm defined in the var_defns.sh

Please hold on the merging. I will work with Lin to add ~/parp/config into the PR this afternoon. You can merge the PR after that.  

This time we have to rely on Lin's test on ecflow to support the AQMv7 implementation. @lgannoaa

**Comment by chan-hoo** [comment]
Got it.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo   Please merge PR952 now.

**Review by chan-hoo — APPROVED** [review]

**Pull request merged**
