### PR TITLE
[develop] Fixing the issue related to NDAS file name change on NOAA HPSS

### LINKED ISSUE #617: NDAS data file name changed
## Description

 
NDAS data file name changed after  20220628 on NOAA HPSS. We need to modify the data pull script if we want to pull that data from NOAA HPSS for the time after June 28, 2022.

## Solution
Modify the data pulling script to reflect that change.

## Requirements**
No other update is needed.

## Acceptance Criteria (Definition of Done)

The NDAS data after June 28, 2022 can be obtained from NOAA HPSS

## Dependencies (optional)
N/A

### PR DESCRIPTION
**Pull request by panll**
## DESCRIPTION OF CHANGES: 

NDAS file names on NOAA HPSS changed after June 28, 2022. This pull request fixed that issue (#617)

### Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [x ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
N/A

## DOCUMENTATION:
N/A
## ISSUE: 

Fixes issue mentioned in #617

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
Thanks for this fix, @panll!  After making the change, did you test a date between 20200226 and 20220627, and also a date after 20220627 to make sure all the logic works correctly?  If so, I'll approve!

**Comment by panll** [comment]
> Thanks for this fix, @panll! After making the change, did you test a date between 20200226 and 20220627, and also a date after 20220627 to make sure all the logic works correctly? If so, I'll approve!

Yes, it was tested on Hera (e.g., 2022062618, 2022062718. Cycle 2022062718 needs the data  of 20220628 for 12 hour forecast). Thanks! @JeffBeck-NOAA

**Comment by JeffBeck-NOAA** [comment]
> > Thanks for this fix, @panll! After making the change, did you test a date between 20200226 and 20220627, and also a date after 20220627 to make sure all the logic works correctly? If so, I'll approve!
> 
> Yes, it was tested on Hera (e.g., 2022062618, 2022062718. Cycle 2022062718 needs the data of 20220628 for 12 hour forecast). Thanks! @JeffBeck-NOAA

Thanks, @panll!  Approving.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1250519477/20230223170516/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Failed on hera: pregen_grid_orog_sfc_climo
2023-02-23 17:40:19 +0000 :: hfe02 :: Task make_lbcs, jobid=42291579, in state DEAD (FAILED), ran for 16.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: MET_ensemble_verification
2023-02-23 17:44:14 +0000 :: hfe11 :: Task make_sfc_climo, jobid=42291646, in state DEAD (FAILED), ran for 20.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
2023-02-23 17:44:13 +0000 :: hfe07 :: Task make_sfc_climo, jobid=42291636, in state DEAD (FAILED), ran for 19.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
2023-02-23 17:44:13 +0000 :: hfe04 :: Task make_sfc_climo, jobid=42291616, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
2023-02-23 17:44:10 +0000 :: hfe03 :: Task make_sfc_climo, jobid=42291619, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
2023-02-23 17:44:09 +0000 :: hfe10 :: Task make_sfc_climo, jobid=42291649, in state DEAD (FAILED), ran for 17.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
2023-02-23 17:44:11 +0000 :: hfe05 :: Task make_sfc_climo, jobid=42291626, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
2023-02-23 17:44:07 +0000 :: hfe05 :: Task make_sfc_climo, jobid=42291632, in state DEAD (FAILED), ran for 19.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
2023-02-23 17:44:06 +0000 :: hfe12 :: Task make_sfc_climo, jobid=42291639, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Succeeded on hera: community_ensemble_2mems_stoch
All experiments completed

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1250519477/20230223193510/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Failed on hera: pregen_grid_orog_sfc_climo
2023-02-23 20:08:12 +0000 :: hfe08 :: Task make_ics, jobid=42297078, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: pregen_grid_orog_sfc_climo
2023-02-23 20:08:12 +0000 :: hfe08 :: Task make_lbcs, jobid=42297079, in state DEAD (FAILED), ran for 19.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
2023-02-23 20:12:06 +0000 :: hfe03 :: Task make_sfc_climo, jobid=42297152, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
2023-02-23 20:12:11 +0000 :: hfe04 :: Task make_sfc_climo, jobid=42297159, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
2023-02-23 20:12:13 +0000 :: hfe06 :: Task make_sfc_climo, jobid=42297158, in state DEAD (FAILED), ran for 23.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: MET_ensemble_verification
2023-02-23 20:12:14 +0000 :: hfe11 :: Task make_sfc_climo, jobid=42297147, in state DEAD (FAILED), ran for 20.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
2023-02-23 20:12:10 +0000 :: hfe02 :: Task make_sfc_climo, jobid=42297161, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
2023-02-23 20:12:13 +0000 :: hfe08 :: Task make_sfc_climo, jobid=42297153, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
2023-02-23 20:12:07 +0000 :: hfe02 :: Task make_sfc_climo, jobid=42297160, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Succeeded on hera: community_ensemble_2mems_stoch
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
2023-02-23 20:12:15 +0000 :: hfe05 :: Task make_sfc_climo, jobid=42297146, in state DEAD (FAILED), ran for 19.0 seconds, exit status=256, try=2 (of 2)
All experiments completed

**Comment by MichaelLueken** [comment]
@panll The Jenkins tests have all passed (the Orion tests were aborted since the machine is still down for maintenance, which is why the report is showing that the build of this commit was aborted, the tests on Cheyenne, Jet, and Gaea all passed).  However, there are issues with the GiHub Action ci-hera-intel-WE tests.  Only the `community_ensemble_2mems_stoch` is passing.  When you ran the Hera Intel tests, did you encounter issues?  I want to get these changes in, but I'm feeling apprehensive moving forward while the Hera GitHub Action tests are failing.  Thanks!

**Comment by panll** [comment]
@MichaelLueken I have no issue on Hera. What kind of error message do you get? This pull request only change NDAS data downloading and will not impact other parts (e.g., make_sfc_climo).

**Comment by MichaelLueken** [comment]
@panll The ci-hera-intel-WE tests are returning:

```
Experiment Failed on hera: pregen_grid_orog_sfc_climo
2023-02-23 17:40:19 +0000 :: hfe02 :: Task make_lbcs, jobid=42291579, in state DEAD (FAILED), ran for 16.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: MET_ensemble_verification
2023-02-23 17:44:14 +0000 :: hfe11 :: Task make_sfc_climo, jobid=42291646, in state DEAD (FAILED), ran for 20.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
2023-02-23 17:44:13 +0000 :: hfe07 :: Task make_sfc_climo, jobid=42291636, in state DEAD (FAILED), ran for 19.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
2023-02-23 17:44:13 +0000 :: hfe04 :: Task make_sfc_climo, jobid=42291616, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
2023-02-23 17:44:10 +0000 :: hfe03 :: Task make_sfc_climo, jobid=42291619, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
2023-02-23 17:44:09 +0000 :: hfe10 :: Task make_sfc_climo, jobid=42291649, in state DEAD (FAILED), ran for 17.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
2023-02-23 17:44:11 +0000 :: hfe05 :: Task make_sfc_climo, jobid=42291626, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
2023-02-23 17:44:07 +0000 :: hfe05 :: Task make_sfc_climo, jobid=42291632, in state DEAD (FAILED), ran for 19.0 seconds, exit status=256, try=2 (of 2)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
2023-02-23 17:44:06 +0000 :: hfe12 :: Task make_sfc_climo, jobid=42291639, in state DEAD (FAILED), ran for 18.0 seconds, exit status=256, try=2 (of 2)
Experiment Succeeded on hera: community_ensemble_2mems_stoch
```

It looks like it might be a space issue or something else.  As noted, the Jenkins tests are fine, it's just the automated tests on Hera that are failing now.  I'll try submitting them again and see what happens.  Thanks!

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1250519477/20230223212013/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Succeeded on hera: pregen_grid_orog_sfc_climo
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
2023-02-23 22:00:16 +0000 :: hfe01 :: Task make_ics, jobid=42300311, in state DEAD (FAILED), ran for 39.0 seconds, exit status=256, try=2 (of 2)
Experiment Succeeded on hera: community_ensemble_2mems_stoch
Experiment Failed on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
2023-02-23 22:00:13 +0000 :: hfe05 :: Task make_ics, jobid=42300319, in state DEAD (FAILED), ran for 45.0 seconds, exit status=256, try=2 (of 2)
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
Experiment Succeeded on hera: MET_ensemble_verification
All experiments completed

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1250519477/20230224142011/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
2023-02-24 15:04:05 +0000 :: hfe01 :: Task run_fcst, jobid=42326696, in state DEAD (FAILED), ran for 106.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
2023-02-24 15:08:14 +0000 :: hfe12 :: Task run_fcst, jobid=42326768, in state DEAD (FAILED), ran for 106.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
2023-02-24 15:08:07 +0000 :: hfe01 :: Task run_fcst, jobid=42326769, in state DEAD (FAILED), ran for 139.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
2023-02-24 15:04:14 +0000 :: hfe07 :: Task run_fcst, jobid=42326679, in state DEAD (FAILED), ran for 120.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
2023-02-24 15:04:08 +0000 :: hfe10 :: Task run_fcst, jobid=42326666, in state DEAD (FAILED), ran for 104.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: MET_ensemble_verification
2023-02-24 15:04:08 +0000 :: hfe07 :: Task run_fcst_mem001, jobid=42326686, in state DEAD (FAILED), ran for 106.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: MET_ensemble_verification
2023-02-24 15:04:08 +0000 :: hfe07 :: Task run_fcst_mem002, jobid=42326687, in state DEAD (FAILED), ran for 104.0 seconds, exit status=256, try=1 (of 1)
Experiment Failed on hera: pregen_grid_orog_sfc_climo
2023-02-24 15:00:17 +0000 :: hfe10 :: Task run_fcst, jobid=42326630, in state DEAD (FAILED), ran for 107.0 seconds, exit status=256, try=1 (of 1)
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
Experiment Succeeded on hera: community_ensemble_2mems_stoch
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
All experiments completed

**Review by MichaelLueken — APPROVED** [review]
@panll Thank you for fixing this issue!  As noted yesterday, the Jenkins tests successfully passed and, ultimately, all of the fundamental tests from the ci-hera-intel-WE tests have passed.  I will now give my approval to these changes.

**Pull request merged**
