### PR TITLE
[production/AQM.v7] update workflow for AQMv7 implementation

### PR DESCRIPTION
**Pull request by JianpingHuang-NOAA**
The PR is used to allow the system to use static fix dir by rocoto workflow for each run test. The purpose is to get rid of creating symbolic link of fix for each run 

## DESCRIPTION OF CHANGES: 

The change is used to update setup.py script

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- [ ] hera.intel
- [ ] orion.intel
- [ ] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [x] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, does the rocoto workflow run without this temporary fix?

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo Yes.  We need to run ~/ush/auto_A1_cp_fix_link_fix_lam.sh  to create fix dir at the begging of the system set up and then never do any symbolic link to the fix dir after that. That is what we want.  This is consist with the way that ECFLOW does.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, do you mean that we should run `auto_A1_cp_fix_link_fix_lam.sh` manually again? 
1) I don't agree with this approach (manual step). Please add the command somewhere in the scripts. 
2) You just remove the part for creating FIXlam, but you didn't change the following sym-link commands for this FIXlam (ln 1193). If they are not necessary either, please remove them together.

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  1. I agree with you that it is not good to do copying fix files manually. But that is what we propose for the AQMv7 implementation (see our implementation instruction at https://docs.google.com/document/d/1QiK_-aQdN3qfcgD3hxyxCDu8KpMVWiDp25-itm3aTzg/edit#heading=h.30j0zll).  You can add them back after the AQMv7 implementation.
  2. I tried to remove Line 1193 in setup.py file, but it failed with make_ics and make_lbs. You can check the run log file, :/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20231031 > vim make_lbcs_2023103100.id_1698759222.log.  Is this what you suggest? If yes, I can not do that since it failed.  The one that I used to open PR has been testing for 4 cycles for 20231030. The results are identical.  Please merge as I propose. For the community use, you can add them back after the AQMv7 implementation.  Thanks !

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, Is the "rocoto" workflow mandatory for the AQM.v7 implementation? It doesn't make sense to me. In the previous PR for ecFlow, it screwed up the rocoto part and the rocoto option didn't work correctly. But you said it would be fine for the AQM implementation. What is the truth?

**Comment by JianpingHuang-NOAA** [comment]
@chan-hoo  The "rocoto" workflow is not a mandatory component of the AQM.v7 implementation. The most recent workflow that you modified continues to create a symbolic link for the "fix" directory with each run. However, it appears that your workflow deletes the "fix" directory and recreates a symbolic link under the package/aqm.v7.0.0 directory each time, which is not the intended behavior. Ideally, the "fix" directory should be established during the initial system setup. Once the "fix" directory is in place, it should not be deleted, and new symbolic links should not be created.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I agree with the concept of the fix directory (removal of the temporary change).  If you make a change correctly, I'll approve this PR. However, 1) you are adding a new "hidden" step for it. 2) Your change for FIXlam is incomplete. For the "ecFlow"-related PRs, I approved them without review because it was the EMC management's decision for the AQM.v7 implementation. As you said, the rocoto option is not required by the AQM.v7 implementation. Therefore, I can't approve any incomplete change.

**Comment by chan-hoo** [comment]
For the record: I'll approve and merge this PR as it is now because the due date for AQM.v7 is today. I'll fix the above issue later.

**Review by chan-hoo — APPROVED** [review]

**Pull request merged**
