### PR TITLE
[production/AQM.v7] Enhancing EE2 compliance for the AQMv7 package

### PR DESCRIPTION
**Pull request by JianpingHuang-NOAA**
## DESCRIPTION OF CHANGES: 

1)  Removed "nowarn" flags in the ufs-weather-model's makefile and fixed "warning" issues related to CCPP

2) Deleted unused scripts and utilities

3)  Fixed the hardcoded issues with AQM_UTIL and UFS_UTILS

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] hera.intel
- [ ] orion.intel
- [ ] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [x] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@chan-hoo it looks like checks are blocking merge here, do you normally bypass that requirement to merge?

**Comment by chan-hoo** [comment]
@BrianCurtis-NOAA, uhm... strange. I didn't change anything. I have no idea what happens.

**Comment by chan-hoo** [comment]
@BrianCurtis-NOAA, I have not met this error before. Do you know how to fix this?

**Review by chan-hoo — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
Looks like it's mandatory a codeowner reviews, i'll have to add myself to codeowners soon. Can you please @chan-hoo

**Comment by MichaelLueken** [comment]
@BrianCurtis-NOAA and @chan-hoo, you should be safe to bypass branch protections for this failure.  A new documentation test has been added.  The current documentation subdirectory in develop is `docs`, rather than the NCO compliant doc.  This is why the test is failing (it is looking for contents in `docs`, rather than `doc`).  This will be addressed in PR #1018.  

Please feel free to merge this PR.

**Pull request merged**
