### PR TITLE
Bug fix for gaea modulefiles.

### PR DESCRIPTION
**Pull request by danielabdi-noaa**
## DESCRIPTION OF CHANGES: 

Bug fix for gaea modulefiles that broke during a recent update. 
- miniconda3 and rocoto should not be loaded in `build_gaea_intel`.
- Do the same for noaacloud modulefiles

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

Made build on gaea successfully. Needs workflow runs through jenkins though (only for gaea)

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DOCUMENTATION:

None

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [X] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
I approve of these changes.  Neither rocoto, alps, or miniconda are required to build the SRW and belong in the wflow_gaea modulefile, rather than the build_gaea_intel modulefile.

**Review by chan-hoo — APPROVED** [review]

**Comment by danielabdi-noaa** [comment]
Gaea seems to work again without this PR. But i still think rocoto/miniconda3 should not be loaded during build so i will leave this PR open.

**Comment by MichaelLueken** [comment]
@danielabdi-noaa I agree that only those libraries required for building should be in the build_gaea_intel modulefile.  I'm fine with keeping this PR open and merging it in.  However, the Gaea [tests](https://jenkins-epic.woc.noaa.gov/blue/organizations/jenkins/ufs-srweather-app%2Fpipeline/detail/PR-407/2/pipeline/236) have failed on Jenkins.

**Comment by danielabdi-noaa** [comment]
@MichaelLueken Yes, i noticed and i believe that is because the miniconda3 version is not specified in`tasks/gaea/miniconda_regional_workflow`. It encountered the same error as before when trying to run the first task.
```
Lmod has detected the following error: Infinite Load Loop detected for module:
"miniconda3/4.12.0" file:
"/lustre/f2/dev/wpo/role.epic/contrib/modulefiles/miniconda3/4.12.0.lua"
While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    miniconda3/4.12.0  /lustre/f2/dev/wpo/role.epic/contrib/modulefiles/miniconda3/4.12.0.lua
```
I have added the version number to it now and hopefully it works. If not, I don't want to disturb what is already working , although i think it can be improved in the future, and will close the PR.

**Review by panll — APPROVED** [review]

**Comment by MichaelLueken** [comment]
The Jenkins pipeline has successfully completed for Gaea.  I will now merge this PR to the official repo.

**Pull request merged**
