### PR TITLE
[develop] Add precipitation-type verification for MET

### PR DESCRIPTION
**Pull request by mkavulich**
## DESCRIPTION OF CHANGES: 
As part of the (soon-to-end 😢) DTC UFS SRW project, one of our final deliverables was to add precipitation-type verification to MET. This PR modifies the Metplus config files to output the relevant ptype statistics for PB2NC and PointStat.

The precipitation-type variables used are described in [this METplus documentation page](https://metplus.readthedocs.io/en/latest/generated/model_applications/precipitation/PointStat_fcstMULTI_obsMETAR_PtypeComparisons.html). This method uses the reported "PRWE" (present weather) field compared to categorical precipitation variables output from the weather model.

### Type of change
- [x] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
Ran verification WE2E tests (`MET_verification`, `MET_ensemble_verification`, and `MET_verification_only_vx`) I did not make any statistical plots, but I confirmed that the appropriate output was contained in the `point_stat*.stat` files. Some of them even had meaningful statistics computed for metrics such as FHO, which isn't a given for such simple test cases! Example line here:

`    4           NA                 NA                       NA         0.05  CNT       4069      0.012486        0.012367             0.012604                4           >=1.0              >=161&&<=163             NA         NA    FHO        539      0.19109         0.13729              0.58998   
`

Ran fundamental tests on Hera as well, but the only changes are to the metplus config files so there should be no impact on the rest of the app.

- [x] hera.intel
- [x] fundamental test suite

## DEPENDENCIES:
None

## DOCUMENTATION:
None

## ISSUE: 
None

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] My changes do not require updates to the documentation (explain).
  - Simply adds additional statistics to existing tasks/tests
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Review by JeffBeck-NOAA — APPROVED** [review]

**Review by panll — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@mkavulich These changes look good to me!

Ran the WE2E coverage tests on Jet (removed the `get_from_HPSS_*` tests due to HPSS being down for extended maintenance this week) and they all passed.  I also ran the MET_verification test and was able to see the newly added `CRAIN`, `CSNOW`, `CFRZR`, and `CICEP` in the `point_stat.*.stat` files.

**Comment by MichaelLueken** [comment]
While the Hera tests had to be aborted and the `get_from_HPSS` tests will fail, submitting Jenkins automated testing for this update now.

**Comment by MichaelLueken** [comment]
> While the Hera tests had to be aborted and the `get_from_HPSS` tests will fail, submitting Jenkins automated testing for this update now.

@mkavulich The tests have completed.

The Hera tests were aborted since the machine is down for maintenance.

On Jet, the `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018`, `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h`, and `get_from_HPSS_ics_RAP_lbcs_RAP` tests failed due to extended downtime on HPSS (05/02-04/2023).  Another test, `community`, also failed.  This failure is due to the test attempting to pull staged data from `/public/data/grids/gfs/0p25deg/grib2`, rather than the EPIC-maintained location, and then attempting to pull the necessary data from HPSS, leading to failure.

On Cheyenne, `nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km` failed in several `run_post` tasks (this has been seen in all PRs since PR #732 was merged) and `grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16`, which failed in the verification and is a known issue.

Since the failures are expected, I can go ahead and move forward with merging this update now, or I can wait and run the Hera tests in the morning, if you would prefer.

**Comment by MichaelLueken** [comment]
The Hera tests have completed.

There are three failures in the Hera GNU tests - The `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200` and `nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16` tests, which is expected since HPSS is still down.  The `get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS` test failed to retrieve gfs.t00z.atmanl.nc from NOMADS, causing the `get_extrn_ics` task to fail and has been a recurring issue since PR #732 was merged.

There are five failures in the Hera Intel tests - The `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200`, `get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2`, and `get_from_HPSS_ics_HRRR_lbcs_RAP` tests failed due to HPSS being down.  The `grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta` test failed in the `run_fcst` task (issue #731).  Finally, the `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR` test failed in PcpCombine task (issue #688).

I will move forward with merging this PR now.

**Pull request merged**
