### PR TITLE
Post merge cleanup: remove old script, consolidate test directories

### PR DESCRIPTION
**Pull request by mkavulich**
## DESCRIPTION OF CHANGES: 
Some cleanup after the merger of the old regional_workflow repository: eliminate the outdated update_fork.pl, and move test script and readme from test/ to tests/ directory.

### Type of change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## TESTS CONDUCTED: 
- [ ] cheyenne.intel
  - [x] used build.sh to build app
  - [ ] fundamental test suite (*pending*)
- [ ] Jenkins

## DEPENDENCIES:
CI testing will have to be updated to account for the new location of build.sh. I have corresponded with @venitahagerty and @danielabdi-noaa to make sure they are in the loop and can apply the appropriate changes.

## DOCUMENTATION:
None

## ISSUE: 
Addresses a few items from #351 

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by danielabdi-noaa** [comment]
@mkavulich I think only a one line change is required to get Jenkins build working so you may as well make it in this PR.
In `.cicd/scripts/srw_build.sh`
```
 # Build and install
-cd ${workspace}/test
+cd ${workspace}/tests
```

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: build
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1099467489/20221025213515/ufs-srweather-app
Build was Successful
If test failed, please make changes and add the following label back:
ci-hera-intel-build

**Comment by mkavulich** [comment]
@danielabdi-noaa Thanks for the tip! I missed that in my search for references to the build script, I have implemented that change.

**Review by danielabdi-noaa — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@mkavulich These changes look good!  I approve these changes.

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: build
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/autoci/pr/1099467489/20221026145011/ufs-srweather-app
Build was Successful
If test failed, please make changes and add the following label back:
ci-jet-intel-build

**Comment by MichaelLueken** [comment]
The CI build tests on Hera and Jet successfully passed.  The Jenkins CI pipeline also successfully passed all build and fundamental testing.  Now merging to authoritative repository.

**Pull request merged**
