### PR TITLE
[develop] Incorporate RRFS_dev1 workflow to SRW and import most tasks

### LINKED ISSUE #538: Incorporate all RRFS_dev1 variables and workflow configurations
## Description

 
A lot of variables and workflow tasks are added in RRFS_dev1 that need to be incorporated back into SRW app. One can not test new j-job and ex-scripts of RRFS_dev1 in SRW app because it does not have all of them. The RRFS_dev1 workflow xml file is one big mess. That coupled with new tasks from the Air-Quality modelling work that @chan-hoo is working on, I see will be a problem. I am not offering a solution for this but @christinaholtNOAA may have a solution for that. Until then, we import all variables and workflow tasks to RRFS_dev1 so that new RRFS_dev1 tasks can be developed and tested in SRW.

## Solution

Incorporate all new variables in `config_defaults.yaml` and all the tasks in `FV3LAM_wflow.xml`. Variables should have some structure f.i. new tasks should have own set of variables under a new section `task_{new_task_name}`. The first priority is to make sure current SRW app tasks work after RRFS_dev1 workflow incorporation. Provide flags to turn on/off flags for new spinup/prod cycle tasks etc. of RRFS_dev1.

Second, add capability to run and generate RRFS workflow for retrospective and realtime runs. Provide a `config.rrfs.yaml` file with RRFS_CONUS_3km domain that will be used for incorporating RRFS_dev1 tasks one by one.

## Requirements**

None

## Acceptance Criteria (Definition of Done)

- Current SRW we2e tests must all pass
- All new variables added in `config_defaults.yaml` and machine specific ones
- All new workflow tasks added to `FV3LAM_wflow.xml`
- Provide a `config.rrfs.yaml` file for development
- RRFS_dev1 workflow generation should be possible in SRW app

### PR DESCRIPTION
**Pull request by danielabdi-noaa**
## DESCRIPTION OF CHANGES: 

I am opening up this PR for feedback per our discussion today. Will keep on working on it or a second PR but it is probably time
to get feedback on it. The tasks for both spinup (cold and warm start) and production cycles pass on CONUS domain 3km resolution as shown below. Although I am pretty sure there is a lot more work to do with other test cases I haven't considered, the new code that is constantly coming from RRFS_dev1 etc. So this is just a start to get atleast a test case running partially and try to keep up with the changes from RRFS_dev1.

It should pass fundamental tests now -- tested on Hera successfully.

Addresses the main issue of incorporating RRFS_dev1 workflow
  - #538

And also adds the following tasks that have successfully passed for the specific test case I considered
  - #486
  - #489
  - #546 
  - #545 
  - #543 
  - #542 
  - #490
  - #491

The `run_archive` test although imported can only be tested with someone with write privilege on HPSS. 

Tagging RRFS_dev1 developers for feedback: @hu5970 @EricJames-NOAA @chunhuazhou @ShunLiu-NOAA @TrevorAlcott-NOAA @guoqing-noaa @hongli-wang @terraladwig @daviddowellNOAA
## Result
Result on the `config.rrfs.yaml` file for the CONUS domain on 3km resolution
```
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202107240000          get_extrn_lbcs                    41445542           SUCCEEDED                   0         1          20.0
202107240000            make_lbcs_00                    41445663           SUCCEEDED                   0         1         154.0
202107240000            make_lbcs_01                    41445664           SUCCEEDED                   0         1         151.0
202107240000            make_lbcs_02                    41445665           SUCCEEDED                   0         1         154.0
202107240000            make_lbcs_03                    41445667           SUCCEEDED                   0         1         151.0
202107240000            make_lbcs_04                    41445668           SUCCEEDED                   0         1         152.0
202107240000            make_lbcs_05                    41445669           SUCCEEDED                   0         1         152.0
202107240000            make_lbcs_06                    41445670           SUCCEEDED                   0         1         155.0
202107240000            make_lbcs_07                    41445671           SUCCEEDED                   0         1         152.0
202107240000            make_lbcs_08                    41445673           SUCCEEDED                   0         1         151.0
202107240000            make_lbcs_09                    41445674           SUCCEEDED                   0         1          89.0
================================================================================================================================
202107240300    process_radarref_spinup                    41452897           SUCCEEDED                   0         1         185.0
202107240300     process_bufr_spinup                    41445544           SUCCEEDED                   0         1          76.0
202107240300           get_extrn_ics                    41445545           SUCCEEDED                   0         1          16.0
202107240300                make_ics                    41445676           SUCCEEDED                   0         1         135.0
202107240300         prep_cyc_spinup                    41445872           SUCCEEDED                   0         1          36.0
202107240300    anal_gsi_input_spinup                    41445873           SUCCEEDED                   0         1         347.0
202107240300    postanal_input_spinup                    41445922           SUCCEEDED                   0         1          21.0
202107240300    cldanl_nonvar_spinup                    41445926           SUCCEEDED                   0         1          93.0
202107240300         run_fcst_spinup                    41445929           SUCCEEDED                   0         1         349.0
202107240300    save_restart_spinup_f001                    41446035           SUCCEEDED                   0         1          33.0
202107240300    run_post_spinup_f000                    41471267           SUCCEEDED                   0         1         126.0
202107240300    run_prdgen_spinup_f000                    41471274           SUCCEEDED                   0         1          38.0
202107240300    run_post_spinup_f001                    41471272           SUCCEEDED                   0         1         115.0
202107240300    run_prdgen_spinup_f001                    41471275           SUCCEEDED                   0         1          38.0
================================================================================================================================
202107240400    process_radarref_spinup                    41452898           SUCCEEDED                   0         1         187.0
202107240400     process_bufr_spinup                    41445547           SUCCEEDED                   0         1          71.0
202107240400         prep_cyc_spinup                    41446051           SUCCEEDED                   0         1          66.0
202107240400    anal_gsi_input_spinup                    41446060           SUCCEEDED                   0         1         314.0
202107240400    postanal_input_spinup                    41446117           SUCCEEDED                   0         1          35.0
202107240400    cldanl_nonvar_spinup                    41446126           SUCCEEDED                   0         1          96.0
202107240400         run_fcst_spinup                    41446148           SUCCEEDED                   0         1         356.0
202107240400    save_restart_spinup_f001                    41446238           SUCCEEDED                   0         1          54.0
202107240400    run_post_spinup_f000                    41471295           SUCCEEDED                   0         1         121.0
202107240400    run_prdgen_spinup_f000                    41471338           SUCCEEDED                   0         1          40.0
202107240400    run_post_spinup_f001                    41471296           SUCCEEDED                   0         1         117.0
202107240400    run_prdgen_spinup_f001                    41471339           SUCCEEDED                   0         1          40.0
================================================================================================================================
202107240500    process_radarref_spinup                    41452899           SUCCEEDED                   0         1         186.0
202107240500     process_bufr_spinup                    41445549           SUCCEEDED                   0         1          75.0
202107240500         prep_cyc_spinup                    41446248           SUCCEEDED                   0         1          59.0
202107240500    anal_gsi_input_spinup                    41451947           SUCCEEDED                   0         1         347.0
202107240500    postanal_input_spinup                    41452170           SUCCEEDED                   0         1          41.0
202107240500    cldanl_nonvar_spinup                    41452303           SUCCEEDED                   0         1          97.0
202107240500         run_fcst_spinup                    41452373           SUCCEEDED                   0         1         362.0
202107240500    save_restart_spinup_f001                    41452611           SUCCEEDED                   0         1          57.0
202107240500    run_post_spinup_f000                    41471297           SUCCEEDED                   0         1         120.0
202107240500    run_prdgen_spinup_f000                    41471340           SUCCEEDED                   0         1          40.0
202107240500    run_post_spinup_f001                    41471298           SUCCEEDED                   0         1         117.0
202107240500    run_prdgen_spinup_f001                    41471341           SUCCEEDED                   0         1          41.0
================================================================================================================================
202107240600    process_radarref_spinup                    41452900           SUCCEEDED                   0         1         187.0
202107240600     process_bufr_spinup                    41445551           SUCCEEDED                   0         1          72.0
202107240600          get_extrn_lbcs                    41445552           SUCCEEDED                   0         1          19.0
202107240600            make_lbcs_00                    41445677           SUCCEEDED                   0         1         152.0
202107240600            make_lbcs_01                    41445678           SUCCEEDED                   0         1         149.0
202107240600            make_lbcs_02                    41445679           SUCCEEDED                   0         1         152.0
202107240600            make_lbcs_03                    41445680           SUCCEEDED                   0         1         153.0
202107240600            make_lbcs_04                    41445682           SUCCEEDED                   0         1         152.0
202107240600            make_lbcs_05                    41445683           SUCCEEDED                   0         1         156.0
202107240600            make_lbcs_06                    41445684           SUCCEEDED                   0         1         151.0
202107240600            make_lbcs_07                    41445685           SUCCEEDED                   0         1         151.0
202107240600            make_lbcs_08                    41445686           SUCCEEDED                   0         1         151.0
202107240600            make_lbcs_09                    41445690           SUCCEEDED                   0         1          88.0
202107240600         prep_cyc_spinup                    41452730           SUCCEEDED                   0         1          64.0
202107240600    anal_gsi_input_spinup                    41452770           SUCCEEDED                   0         1         339.0
202107240600    postanal_input_spinup                    41452827           SUCCEEDED                   0         1          38.0
202107240600    cldanl_nonvar_spinup                    41452865           SUCCEEDED                   0         1         103.0
202107240600         run_fcst_spinup                    41452901           SUCCEEDED                   0         1         380.0
202107240600    save_restart_spinup_f001                    41453899           SUCCEEDED                   0         1          63.0
202107240600    run_post_spinup_f000                    41471299           SUCCEEDED                   0         1         119.0
202107240600    run_prdgen_spinup_f000                    41471342           SUCCEEDED                   0         1          42.0
202107240600    run_post_spinup_f001                    41471300           SUCCEEDED                   0         1         117.0
202107240600    run_prdgen_spinup_f001                    41471343           SUCCEEDED                   0         1          42.0
================================================================================================================================
202107240700    process_radarref_spinup                    41452902           SUCCEEDED                   0         1         185.0
202107240700     process_bufr_spinup                    41445804           SUCCEEDED                   0         1          78.0
202107240700         prep_cyc_spinup                    41453977           SUCCEEDED                   0         1          63.0
202107240700    anal_gsi_input_spinup                    41454107           SUCCEEDED                   0         1         343.0
202107240700    postanal_input_spinup                    41454316           SUCCEEDED                   0         1          40.0
202107240700    cldanl_nonvar_spinup                    41454443           SUCCEEDED                   0         1         101.0
202107240700         run_fcst_spinup                    41454645           SUCCEEDED                   0         1         368.0
202107240700    save_restart_spinup_f001                    41456703           SUCCEEDED                   0         1          73.0
202107240700    run_post_spinup_f000                    41471301           SUCCEEDED                   0         1         123.0
202107240700    run_prdgen_spinup_f000                    41471345           SUCCEEDED                   0         1          43.0
202107240700    run_post_spinup_f001                    41471302           SUCCEEDED                   0         1         121.0
202107240700    run_prdgen_spinup_f001                    41471344           SUCCEEDED                   0         1          43.0
================================================================================================================================
202107240800    process_radarref_spinup                    41468567           SUCCEEDED                   0         1         187.0
202107240800     process_bufr_spinup                    41468659           SUCCEEDED                   0         1          85.0
202107240800         prep_cyc_spinup                    41468660           SUCCEEDED                   0         1          71.0
202107240800    anal_gsi_input_spinup                    41468706           SUCCEEDED                   0         1         347.0
202107240800    postanal_input_spinup                    41469056           SUCCEEDED                   0         1          41.0
202107240800    cldanl_nonvar_spinup                    41469064           SUCCEEDED                   0         1         102.0
202107240800         run_fcst_spinup                    41469105           SUCCEEDED                   0         1         394.0
202107240800    save_restart_spinup_f001                    41469343           SUCCEEDED                   0         1          65.0
202107240800    run_post_spinup_f000                    41471308           SUCCEEDED                   0         1         121.0
202107240800    run_prdgen_spinup_f000                    41471346           SUCCEEDED                   0         1          41.0
202107240800    run_post_spinup_f001                    41471309           SUCCEEDED                   0         1         120.0
202107240800    run_prdgen_spinup_f001                    41471347           SUCCEEDED                   0         1          43.0
================================================================================================================================
202107240900    process_radarref_prod                    41469408           SUCCEEDED                   0         1         192.0
202107240900       process_bufr_prod                    41469477           SUCCEEDED                   0         1          86.0
202107240900           prep_cyc_prod                    41469594           SUCCEEDED                   0         1          72.0
202107240900     anal_gsi_input_prod                    41469742           SUCCEEDED                   0         1         372.0
202107240900     postanal_input_prod                    41469892           SUCCEEDED                   0         1          45.0
202107240900      cldanl_nonvar_prod                    41469937           SUCCEEDED                   0         1         104.0
202107240900           run_fcst_prod                    41469957           SUCCEEDED                   0         1         625.0
202107240900    save_restart_prod_f1                    41470289           SUCCEEDED                   0         1          71.0
202107240900           run_post_f000                    41470837           SUCCEEDED                   0         1         120.0
202107240900           run_post_f001                    41471174           SUCCEEDED                   0         1         120.0
202107240900           run_post_f002                    41471175           SUCCEEDED                   0         1         124.0
202107240900           run_post_f003                    41471176           SUCCEEDED                   0         1         122.0
202107240900         run_prdgen_f000                    41470957           SUCCEEDED                   0         1          37.0
202107240900         run_prdgen_f001                    41471205           SUCCEEDED                   0         1          38.0
202107240900         run_prdgen_f002                    41471206           SUCCEEDED                   0         1          37.0
202107240900         run_prdgen_f003                    41471207           SUCCEEDED                   0         1          38.0
202107240900        python_maps_full                    41554794           SUCCEEDED                   0         1         273.0
202107240900           python_skewts                    41554795           SUCCEEDED                   0         1         298.0
202107240900               run_clean                    41509831           SUCCEEDED                   0         1          32.0
================================================================================================================================
```

## Plots
Cool graphics from `pygraf` not the one we already have in SRW i.e.`plot_allvars`. 
Some "colorful" ones:

wspeed_full_10m_f000
temp_full_sfc_f000
pres_full_sfc_f000
hlcy_full_sr01_f000

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [X] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [X] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:

To be investigated

## DOCUMENTATION:

Definately needs a lot of documentation once this PR is ready.

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [X] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1199119157/20230125035010/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1199119157/20230125150519/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Succeeded on hera: pregen_grid_orog_sfc_climo
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
Experiment Succeeded on hera: community_ensemble_2mems_stoch
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
Experiment Succeeded on hera: MET_ensemble_verification
All experiments completed

**Comment by hu5970** [comment]
We need to checkout the system and test it to learn more details of this big PR. But from the task list of each cycle and the run time of each task, it looks good. Thanks.

**Comment by panll** [comment]
Tests failed on Hera. The error messages are:
  mkdir: cannot create directory '/postprd': Read-only file system
/scratch2/BMC/fv3lam/lpan/test/review/01272023/test/ufs-srweather-app/ush/bash_utils/filesys_cmds_vrfy.sh: line 190: cd: /postprd/000: No such file or directory
End JREGIONAL_RUN_POST at Sun Jan 29 00:50:25 UTC 2023 with error code 1 (time elapsed: 00:00:01)
@danielabdi-noaa

**Comment by danielabdi-noaa** [comment]
@panll Thanks for testing. I wasn't paying attention to "community" mode so there was a bug in post-processing that I have fixed now. The github actions fundamental test done in this PR was run in NCO mode so it failed to spot it.

**Comment by JeffBeck-NOAA** [comment]
@panll, thank you for testing!  @danielabdi-noaa, are there no community mode tests in GitHub Actions? I know we have them in the Jenkins tests.  Thanks!

**Comment by MichaelLueken** [comment]
With the removal of RRFS-related features (please see PR #893), it is safe to close this PR now.

**Pull request closed without merging**
