### PR TITLE
Test/jenkins

### PR DESCRIPTION
**Pull request by danielabdi-noaa**
## DESCRIPTION OF CHANGES: 
Temporary PR to test PR #348  with Jenkins modifcations from PR #333 .
Please ignore it as I will remove the PR once the tests are done.

### CODE REVIEW

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
STOP

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1065920343/20220925040513/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 1 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Succeeded on hera: custom_GFDLgrid
All experiments completed

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by dshawul** [comment]
Test

**Comment by danielabdi-noaa** [comment]
Test

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Comment by danielabdi-noaa** [comment]
REBUILD

**Pull request closed without merging**
