### PR TITLE
Update Spack Stack Location for NOAA Cloud

### PR DESCRIPTION
**Pull request by EdwardSnyder-NOAA**
## DESCRIPTION OF CHANGES: 
Update Spack Stack location in the NOAA Cloud build file.

## TESTS CONDUCTED: 
Ran the comprehensive suite of tests on AWS through Jenkins successfully. More work is needed to setup Azure and GCP with Jenkins. As a result, I ran a single E2E test on Azure and GCP manually. Both of these tests were successful.

## DEPENDENCIES:
None.

## DOCUMENTATION:
No updates.

## CONTRIBUTORS (optional): 
@kgerheiser who updated the Spack HPC-Stack on NOAA Cloud.

### CODE REVIEW

**Review by mark-a-potts — APPROVED** [review]

**Review by gspetro-NOAA — APPROVED** [review]

**Comment by kgerheiser** [comment]
The builds failed on Hera and Jet. Do these Jenkins tests run on the cloud platforms?

**Comment by gspetro-NOAA** [comment]
> The builds failed on Hera and Jet. Do these Jenkins tests run on the cloud platforms?

@kgerheiser Since this adjustment is only for the noaacloud build modulefile, it shouldn't matter for this PR whether builds pass or fail on Hera and Jet, no? (Of course, we'd want to see why builds are failing there, but it shouldn't be due to this PR, since nothing affecting Hera or Jet was changed...)
@EdwardSnyder-NOAA Thoughts? Are Hera/Jet builds failing elsewhere?

**Comment by EdwardSnyder-NOAA** [comment]
@kgerheiser - we have the capability to run tests on the cloud platforms through Jenkins, we just don't have the cloud tests integrated into GitHub yet. I was able to build the SRW App on AWS and run the comprehensive tests on it through Jenkins on Friday. The Miniconda3 used for the AWS build was missing on GCP and Azure, but I've resolved that and ran a single E2E on GCP, which was a successful run. I'm still having spack issues on Azure but you are already aware of that.

@gspetro-NOAA - Both Hera and Jet are crashing through our Jenkins pipeline with other PRs. I believe the Hera issue is related to a variable in `hera.sh` and the Jet issue is related to a syntax error within our pipeline script. I'll investigate more into these issues tomorrow.

**Comment by kgerheiser** [comment]
Fixed the meta-moduels on Azure.

And for Miniconda this should be loaded beforehand as well:

```
module use /contrib/spack/modulefiles
```

And that will bring `miniconda/3.9.7` into your modulepath for the meta-module to load.

And then when loading `stack-python` Miniconda will load correctly.

**Comment by EdwardSnyder-NOAA** [comment]
Thanks @kgerheiser! 

The SRW App builds and runs on AWS, Azure, and GCP with the new spack stack location. More work is needed to integrate the Jenkins E2E test pipeline with Azure, GCP, Jet, and Hera, which will be addressed in a future PRs.

**Comment by kgerheiser** [comment]
Thanks for running those tests. This is some good real world testing.

**Pull request merged**
