### PR TITLE
Changes to Externals.cfg and add CODEOWNERS and PR template files

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
These changes work on Jet.  Can others @JulieSchramm @mkavulich @gsketefian @BenjaminBlake-NOAA @RatkoVasic-NOAA test on Hera, WCOSS and Cheyenne?

I also added the PR template and CODEOWNERS files from the regional_workflow repository.

Thanks!

- Jeff

### CODE REVIEW

**Comment by JulieSchramm** [comment]
I will test on Cheyenne.

**Comment by BenjaminBlake-NOAA** [comment]
I can test on WCOSS but might not finish until sometime tomorrow, hope that's fine.

**Comment by JeffBeck-NOAA** [comment]
Sounds good.  Thanks, Ben!

**Comment by JulieSchramm** [comment]
Out-of-the-box case builds and runs to completion on Cheyenne.  Results look reasonable.

**Comment by BenjaminBlake-NOAA** [comment]
@JeffBeck-NOAA I haven't forgot about testing this PR.  Sorry I haven't been able to finish the WCOSS testing just yet but we should hopefully be good to go in the next day or so.

**Comment by BenjaminBlake-NOAA** [comment]
Just completed testing the workflow on the Cray.  One minor change will be required to src/build_forecast.sh.  Is there an easy way to do that on GitHub?  Will begin testing on the Dell next.

**Comment by mkavulich** [comment]
@BenjaminBlake-NOAA You can make modifications directly through github by clicking on the 
"JeffBeck-NOAA:master" link underneath the title of this PR (the source branch), navigating to the appropriate file (click "src", then "build_forecast.sh") then click the pencil icon at top-right (if you mouse over the icon it will say "Edit this file". Make the appropriate changes, add a commit message, then click "commit changes". That will commit directly to this branch, which should immediately update the PR.

**Comment by BenjaminBlake-NOAA** [comment]
@mkavulich Ok cool, I figured something like that would be possible.  I did that and it created a PR to Jeff's branch, which he'll have to approve, and then it should (hopefully!) show up here.

**Comment by BenjaminBlake-NOAA** [comment]
Everything looks good on the Dell, I will approve this PR.  There are still a couple of outstanding issues related to running on WCOSS that eventually need to be addressed but they are relatively minor and I haven't had a chance to work on them yet.

**Pull request merged**
