### PR TITLE
[develop] Remove redundancies in loading the run-time python environment.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 

- Remove all tasks' modulefiles that _only_ load the python environment, or nothing at all. One's that do more than that were left as-is.
- Load the python module at run time by default when no local file exists.
- Rename the common python module to be consistent across all platforms, and to remove "regional_workflow" reference in module name in favor of "srw".

This simplification should help as we add more and more tasks that need the same python modules loaded. This approach will still allow us to keep a file for any tasks that need more than the base python environment, or when the base python environment should _not_ be loaded.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DOCUMENTATION:

I'm not sure.

## ISSUE: 

n/a

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@christinaholtNOAA These changes look good!  I was also able to run the coverage WE2E tests on Jet (with the exception of the `get_from_HPSS_*` tests) without issue.

**Review by mkavulich — APPROVED** [review]
Looks like some good, much-needed cleanup/consolidation of the modulefiles

**Comment by MichaelLueken** [comment]
On Cheyenne GNU, the `nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km` failed in several of the `run_post` tasks.  This has been a continuing issue since PR #732 was merged and is likely due to issue #652.

On Hera GNU, the `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200`, `get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS`, and `nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16` tests failed due to extended downtime for HPSS.  The `MET_verification_only_vx` test also failed, but the Jenkins workspace directories have been wiped, so I'm unsure what caused the failure.

On Hera Intel, the `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200`, `get_from_HPSS_ics_GDAS_lbcs_GDAS_fmt_netcdf_2022040400_ensemble_2`, and `get_from_HPSS_ics_HRRR_lbcs_RAP` tests failed due to HPSS being down. The `grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta` test failed, but since the directories were wiped, I'm not sure the cause of the failure (though it is likely due to issue https://github.com/ufs-community/ufs-srweather-app/issues/731). Finally, the `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR` test failed (likely due to issue https://github.com/ufs-community/ufs-srweather-app/issues/688).

On Jet, the `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018`, `get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h`, and `get_from_HPSS_ics_RAP_lbcs_RAP` tests failed due to extended downtime on HPSS (05/02-04/2023). Another test, `community`, also failed. This failure is due to the test attempting to pull staged data from /public/data/grids/gfs/0p25deg/grib2, rather than the EPIC-maintained location, and then attempting to pull the necessary data from HPSS, leading to failure.

I'm rerunning the `MET_verification_only_vx` test on Hera GNU to ensure that the test is working properly, then I will go ahead and merge this work.

**Comment by MichaelLueken** [comment]
I have successfully ran the `MET_verification_only_vx` test on Hera GNU.  I will now merge this work.

**Pull request merged**
