### PR TITLE
[develop] [bug fix]  Adding missing Intel variable for PW Azure 

### PR DESCRIPTION
**Pull request by EdwardSnyder-NOAA**
## DESCRIPTION OF CHANGES: 

The SRW App still fails on the PW Azure instance. It appears that the compute node needs to be in the same zone as the controller node. To achieve this, the compute node instance type needs to change, which is failing because of a missing intel variable. This PR adds this missing intel variable when running on Azure.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] derecho.intel
- [ ] gaea.intel
- [ ] hera.gnu
- [ ] hera.intel
- [ ] hercules.intel
- [ ] jet.intel
- [ ] orion.intel
- [ ] wcoss2.intel
- [X] NOAA Cloud (indicate which platform)
- Azure; [log file](https://jenkins.epic.oarcloud.noaa.gov/job/ufs-srweather-app/job/nightly/357/console) for this PR passing on the nightly Jenkins build 
- [X] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [X] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@EdwardSnyder-NOAA -

These changes look good to me!  I see from the nightly build that both the Functional WorkflowTaskTests and Test phases successfully passed.

I ran the fundamental tests on Hera and they all passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              18.91
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE              11.41
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              30.72
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024121  COMPLETE              56.96
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241211145  COMPLETE              32.22
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024121114570  COMPLETE              57.89
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             208.11
```
Additionally, the Functional WorkflowTaskTests script was also run on Hera and successfully passed:
```
# Try hera with the first few simple SRW tasks ...
run_make_grid: COMPLETE
run_get_ics: COMPLETE
run_get_lbcs: COMPLETE
run_make_orog: COMPLETE
run_make_sfc_climo: COMPLETE
run_make_ics: COMPLETE
run_make_lbcs: COMPLETE
run_fcst: COMPLETE
run_post: COMPLETE
```
Approving this PR now.

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Review by rickgrubin-noaa — APPROVED** [review]
LGTM, approved.

**Comment by MichaelLueken** [comment]
@EdwardSnyder-NOAA -

There are currently issues with the documentation that has nothing to do with the changes you have made.  I'll need to open a PR in your fork to address a site redirect.  There is also an issue with the NCEP site currently being down.  I have opened PR [#2](https://github.com/EdwardSnyder-NOAA/ufs-srweather-app/pull/2) in your fork to address the site redirect.  I'll wait until the issue with the NCEP site has been addressed, then I will merge this work.

**Comment by MichaelLueken** [comment]
After discussing with @gspetro-NOAA, I will merge this work to develop now and will check if https://www.ncep.noaa.gov properly loads in the morning.

This will lead to a red X on develop, but again, it should clear up by the morning (hopefully).

**Pull request merged**
