### PR TITLE
[develop] Port SRW-AQM to Orion and Hercules

### LINKED ISSUE #1036: [SRW-AQM] Need to port SRW-AQM to Orion
## Description

 

SRW-AQM is not available on Orion.

### LINKED ISSUE #1037: [SRW-AQM] Need to port SRW-AQM to Hercules
## Description

 

SRW-AQM is not available on Hercules

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Port SRW-AQM to Orion and Hercules

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [x] hera.intel
- [x] orion.intel
- [x] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 

Fixes Issues #1036 and #1037 

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@chan-hoo -

The AQM WE2E test,  `aqm_grid_AQM_NA13km_suite_GFS_v16`, successfully passed on Orion:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
aqm_grid_AQM_NA13km_suite_GFS_v16_20240404125225                   COMPLETE            6370.25
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            6370.25
```
and Hercules:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
aqm_grid_AQM_NA13km_suite_GFS_v16_20240404153142                   COMPLETE            5544.63
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            5544.63
```
Approving this PR now.

**Comment by chan-hoo** [comment]
@MichaelLueken, thanks for approving !!! :)

**Comment by chan-hoo** [comment]
@RatkoVasic-NOAA, please review this pr :) :)

**Comment by RatkoVasic-NOAA** [comment]
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
aqm_grid_AQM_NA13km_suite_GFS_v16_20240405121816                   COMPLETE            6375.65
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            6375.65
```
It passed on Orion. On Hercules second run hit the wallclock limit, but everything else was fine. Since Michael already got Hercules run OK, I'm going to approve.

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by chan-hoo** [comment]
@RatkoVasic-NOAA, thank you so much for your approval !!! :)

**Comment by MichaelLueken** [comment]
@chan-hoo -

All automated Jenkins tests successfully passed.  Moving forward with merging this PR now.

**Pull request merged**
