### PR TITLE
[develop] Fix overwriting user-defined WRTCMP* values.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 

This change is needed so that when users provide their own WRTCMP* variables in config.yaml alongside a pre-defined domain, their changes do not get overwritten.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

EDIT: I didn't mention how I tested that this does what it is supposed to do.

I generated a test config.yaml through the WE2E run tests script and then edited the fully formed config.yaml in ush to add one of the WRTCMP* entries and confirm that it was indeed overwritten in the var_defns.sh file when I ran the ush generate workflow script.

The additional entry looked like this:
```
task_run_forecast:
  WRTCMP_stdlat2: nonsense
```

I did not follow that up to make sure that the entry propagated to other configuration files. I assumed that SRW internals know what to do with that value once it's "properly" set.

## DEPENDENCIES:

n/a

## DOCUMENTATION:

n/a

## ISSUE: 

This is related to a problem @natalie-perlin was reporting in this week's meeting. I didn't see an obvious Issue related to the problem, though.

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by natalie-perlin** [comment]
I'm testing this on Orion by running a default community test. Having troubles getting get_extrn_ics and get_extrn_ics working. After checking out the PR and merging with the updated develop branch: 

```
cd ./usf-srweather-app
./devbuild.sh -p=orion
cd ./ush
cp -pv config.community.yaml config.yaml
vim config.yaml                    # set MACHINE: orion and ACCOUNT: epic
vim machine/orion.yaml      # EXTRN_MDL_DATA_STORES: disk aws nomads
cd ../
module use $PWD/modulefiles
module load wflow_orion
conda activate workflow_tools
./generate_FV3LAM_wflow.py
export EXPTDIR=<EXPTDIR>  # as indicated after generating workflow
cd $EXPTDIR
rocotorun -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10
```

It produces errors in retrieving files:

```
09/11/23 23:11:38 CDT :: FV3LAM_wflow.xml :: Cycle 201906151800, Task get_extrn_ics, jobid=14964609, in state DEAD (FAILED), ran for 15.0 seconds, exit status=256, try=1 (of 1)
09/11/23 23:11:38 CDT :: FV3LAM_wflow.xml :: Cycle 201906151800, Task get_extrn_lbcs, jobid=14964610, in state DEAD (FAILED), ran for 6.0 seconds, exit status=256, try=1 (of 1)
```

End of a log file get_extrn_ics_2019061518.log:
```
Traceback (most recent call last):
  File "/work/noaa/epic/nperlin/SRW/ufs-srweather-app/ush/retrieve_data.py", line 1081, in <module>
    main(sys.argv[1:])
  File "/work/noaa/epic/nperlin/SRW/ufs-srweather-app/ush/retrieve_data.py", line 797, in main
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: You must provide an input_file_path when choosing  disk as a data store!
End exregional_get_extrn_mdl_files.sh at Tue Sep 12 04:11:21 UTC 2023 with error code 1 (time elapsed: 00:00:01)
FATAL ERROR:
ERROR:
  From script:  "JREGIONAL_GET_EXTRN_MDL_FILES"
  Full path to script:  "/work/noaa/epic/nperlin/SRW/ufs-srweather-app/jobs/JREGIONAL_GET_EXTRN_MDL_FILES"
Call to ex-script corresponding to J-job "JREGIONAL_GET_EXTRN_MDL_FILES" failed.
Exiting with nonzero status.
End JREGIONAL_GET_EXTRN_MDL_FILES at Tue Sep 12 04:11:21 UTC 2023 with error code 1 (time elapsed: 00:00:01)

```
What needs to be done to have the ICS and LBCS paths set up? The machine file orion.yaml has the following set up:
`TEST_EXTRN_MDL_SOURCE_BASEDIR: /work/noaa/epic/role-epic/contrib/UFS_SRW_data/develop/input_model_data`

**Comment by natalie-perlin** [comment]
Similar issue with run_get_ics and run_get_lbcs on Hera. 
Set the following in ./ush/machine/hera.yaml:
`EXTRN_MDL_DATA_STORES: disk aws nomads`

**Comment by mkavulich** [comment]
@natalie-perlin The `TEST_EXTRN_MDL_SOURCE_BASEDIR` is for testing purposes only. The `run_WE2E_tests.py` script takes this value and places it in the resulting `config.yaml` file in the necessary locations. If you aren't running using the testing script, you'll need to set `EXTRN_MDL_SOURCE_BASEDIR_ICS` and `EXTRN_MDL_SOURCE_BASEDIR_LBCS` [as described in the users guide](https://ufs-srweather-app.readthedocs.io/en/latest/BuildingRunningTesting/RunSRW.html#general-instructions-for-all-systems).

**Comment by natalie-perlin** [comment]
@mkavulich - thank you for explaining the difference, that's helpful to know!! Working on it now.

**Comment by natalie-perlin** [comment]
1st testing approach is done using a `config.community.yaml` example.

cp config.community.yaml config.community
Edit data location for ICS and LBCS ([comment by Eddie](https://github.com/ufs-community/ufs-srweather-app/issues/909#issuecomment-1716319162))
Set the following in config.yaml to overwrite grid defaults from predef_grid_params.yaml:

```
task_run_fcst:
  LAYOUT_X: 6
  LAYOUT_Y: 6
  QUILTING: true
  QUILTING:
    WRTCMP_write_groups: 1
    WRTCMP_write_tasks_per_group: 4
```

A workflow is then generated using generate_FV3LAM_wflow.py. Go to the experiment directory, and run 

`rocotorun -w FV3LAM_wflow.xml -d FV3LAM_wflow.db -v 10`

The first task of grid generation fails with the message:
```
Traceback (most recent call last):
  File "/work/noaa/epic/nperlin/SRW/ufs-srw-dev/ush/link_fix.py", line 408, in <module>
    verbose=cfg["workflow"]["VERBOSE"],
KeyError: 'workflow'
/work/noaa/epic/nperlin/SRW/ufs-srw-dev/ush/bash_utils/print_msg.sh: line 192: BASH_SOURCE[1]: unbound variable
FATAL ERROR:
ERROR:
  From script:  ""
  Full path to script:  ""
Call to function to create symlinks to the various grid and mosaic files
failed.
```

Is specifying task_run_fcst incorrect, and how it needs to be properly set?

**Comment by natalie-perlin** [comment]
Simple approach is for testing, no runtime needed.

- edit config.yaml, add domain decomposition variables including WRTCMP_write_tasks_per_group
- generate a workflow
- verify that a var_defns.sh in experiment directory has the same WRTCMP_write variables as in config.yaml

Set in config.yaml:
```
LAYOUT_X='6'
LAYOUT_Y='6'
WRTCMP_write_groups='1'
WRTCMP_write_tasks_per_group='4'
```

Resulted in var_defns.sh:

```
LAYOUT_X='6'
LAYOUT_Y='6'
BLOCKSIZE='40'
# [task_run_fcst.QUILTING]
WRTCMP_write_groups='1'
WRTCMP_write_tasks_per_group='4'

PRINT_ESMF='FALSE'
PE_MEMBER01='38'
WRTCMP_write_groups='1'
WRTCMP_write_tasks_per_group='2'
```

 The variables WRTCMP_write_tasks_per_group appear twice in var_defns.sh, first time with a value set in config.yaml, and another one set as a default.
 This is not an expected behavior.

**Comment by christinaholtNOAA** [comment]
When you specify the setting in the config.yaml file, it must be specified with exactly the same structure as in the config_defaults.yaml file. In this case, your input config.yaml should read:

```
task_run_fcst:
  LAYOUT_X: 6
  LAYOUT_Y: 6
  QUILTING: true
  WRTCMP_write_groups: 1
  WRTCMP_write_tasks_per_group: 4

```

**Comment by natalie-perlin** [comment]
@christinaholtNOAA - 
 Specifying these parameters with no staggering (or levels) does solve the issue.  Set in config.yaml as following:  
 ```
task_run_fcst:
  LAYOUT_X: 6
  LAYOUT_Y: 6
  QUILTING: true
  WRTCMP_write_groups: 1
  WRTCMP_write_tasks_per_group: 4
```

Result in var_defns.sh:

```
LAYOUT_X='6'
LAYOUT_Y='6'
BLOCKSIZE='40'
QUILTING='TRUE'
PRINT_ESMF='FALSE'
PE_MEMBER01='40'
WRTCMP_write_groups='1'
WRTCMP_write_tasks_per_group='4'
```

**Review by natalie-perlin — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@christinaholtNOAA - This was tested on Hera and the expected behavior was seen.  Approving this PR now.

**Comment by MichaelLueken** [comment]
The two tests that failed for the Jenkins tests on Hera Intel were reran and successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2        COMPLETE               6.94
custom_ESGgrid_Central_Asia_3km                                    COMPLETE              24.04
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE              30.98
```
Moving forward with merging this work now.

**Pull request merged**
