### PR TITLE
src/machine-setup.sh: don't purge on gaea

### PR DESCRIPTION
**Pull request by climbfuji**
Change `src/machine-setup.sh` so that no `module purge` is done on gaea, or hell will break loose.

This PR is for the upcoming SRW App public release 1.0, not sure to which branch should go to. 

A corresponding PR is required for UFS_UTILS (https://github.com/NOAA-EMC/UFS_UTILS/pull/189). There is also an update for the ufs-weather-model, which will be part of this PR (not yet): https://github.com/ufs-community/ufs-weather-model/pull/248

### CODE REVIEW

**Review by JulieSchramm — APPROVED** [review]
Can you also merge this change to the release/public-v1 branch?

**Comment by climbfuji** [comment]
> Can you also merge this change to the release/public-v1 branch?

I don't even know to which branch this should go, maybe only to `release/public-v1` for now. @mkavulich @JeffBeck-NOAA

**Comment by JeffBeck-NOAA** [comment]
@climbfuji, this should go into master and release/public-v1.  We can merge this PR and then open an identical one to release/public-v1.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
Ok, ready to go. Please send it to the public release afterwards. You can simply cherry-pick commit 53801df7337b80aed02a96e020ec268237e57974. Thanks.

**Pull request merged**
