### PR TITLE
Feature/doc updates

### PR DESCRIPTION
**Pull request by jwolff-ncar**
## DESCRIPTION OF CHANGES: 
Updating links for pulling model initialization data

## TESTS CONDUCTED: 
No required - documentation update only

### CODE REVIEW

**Comment by jwolff-ncar** [comment]
@JulieSchramm Please take a look at this PR. I am not sure why the changes I made earlier are still showing as differences because I think you merged those. If I did something wrong or need to update something and issue a new PR, please let me know.

**Comment by JulieSchramm** [comment]
@jwolff-ncar The changes for the AWS data were merged in PR #105
yesterday.  Did you update your feature/doc_updates branch with the
authoritative release/public-v1 branch?

**Comment by jwolff-ncar** [comment]
Dang that git push step...! I think we are good now? @JulieSchramm Let me know if I need to do anything else.

**Comment by JulieSchramm** [comment]
That looks good.

**Review by JulieSchramm — APPROVED** [review]

**Pull request merged**
