### PR TITLE
[develop] Update ufs-weather-model hash and UPP hash and use upp-addon-env spack-stack environment

### LINKED ISSUE #1138: SRW forecast runs do not use threading even if `OMP_NUM_THREADS_RUN_FCST` is set > 1
## Expected behavior
SRW contains the config variable `OMP_NUM_THREADS_RUN_FCST` which should activate threading when set greater than 1 (default in SRW is 2, so should be every run unless specified otherwise). 

## Current behavior
Threading is not activated for the weather model, no matter what `OMP_NUM_THREADS_RUN_FCST` is set to. You can observe this by opening the run_fcst log file for any SRW run; here is just one example from the WE2E test `grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0`:

```
* . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
     PROGRAM ufs-weather-model HAS BEGUN. COMPILED       0.00     ORG: np23
     STARTING DATE-TIME  OCT 14,2024  17:32:13.156  288  MON   2460598
...
...
atmosphere_init: current_time_seconds =       0.0
Using n_split from the namelist: 005
 Off center implicit scheme param=   1.000000
  p_fac=  0.1000000
Using n_sponge : 024
Using non_ortho :       T
 Starting PEs :           25
 Starting Threads :            1
 Cubed-sphere, single face domain decomposition
whalo =    3, ehalo =    3, shalo =    3, nhalo =    3
...
```

Note the line "`Starting Threads :            1`", which indicates only a single thread is being used, despite us requesting 2.

## Machines affected
Confirmed on Orion, Hera, and Derecho, but this should affect all machines.

## Steps To Reproduce
1. Run any SRW test that contains a run_fcst task
2. View the run_fcst log file, and confirm that threading is not being used, despite `OMP_NUM_THREADS_RUN_FCST=2` being the default

## Detailed Description of Fix
I honestly don't know how to fix this. I am confused by the latest instructions on how to set OMP_NUM_THREADS for the weather model. Currently, the app sets the threading value in the `model_configure` file (`atmos_nthreads:          1`, but [this variable has been deprecated for years](https://github.com/ufs-community/ufs-weather-model/pull/561) (as a side note, [so has `PE_MEMBER01`](https://github.com/ufs-community/ufs-weather-model/pull/654), which is also still being set) so the setting has no effect. However, if I follow [the instructions in the weather model users guide](https://ufs-weather-model.readthedocs.io/en/develop/FAQ.html#how-do-i-set-the-total-number-of-tasks-for-my-job) (setting `ATM_omp_num_threads:            2` in `ufs.configure`), I get behavior that I don't understand from the model: it seems to be using way fewer MPI tasks than expected, and so fails with a corresponding error message:

```
* . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * .
     PROGRAM ufs-weather-model HAS BEGUN. COMPILED       0.00     ORG: np23
     STARTING DATE-TIME  OCT 14,2024  17:23:00.856  288  MON   2460598
...
...
atmosphere_init: current_time_seconds =       0.0
Using n_split from the namelist: 005
 Off center implicit scheme param=   1.000000
  p_fac=  0.1000000
Using n_sponge : 024
Using non_ortho :       T
 Starting PEs :           11
 Starting Threads :            2

FATAL from PE     3: mpp_domains_define.inc: not all the pe_end are in the pelist


FATAL from PE     1: mpp_domains_define.inc: not all the pe_end are in the pelist


FATAL from PE     2: mpp_domains_define.inc: not all the pe_end are in the pelist


FATAL from PE     4: mpp_domains_define.inc: not all the pe_end are in the pelist
...
...
```
Note the entry ` Starting PEs :           11`, which doesn't make any sense to me with the settings provided (identical to the first test except for setting `ATM_omp_num_threads:            2` in `ufs.configure`) and with 30 cores allocated.

Clearly there is something I am missing, but I don't have the time to dig deeper into this. However, this is something that should be solved sooner rather than later, as it likely represents a huge waste of resources due to not using threads that we expect to use (and likely impacts any external groups using recent SRW code to run the weather model).

## Additional Information (optional)
I believe this bug was introduced in #1050, but I can not confirm that that is the case.

### PR DESCRIPTION
**Pull request by MichaelLueken**
## DESCRIPTION OF CHANGES: 
* Update ufs-weather-model hash to [38a29a6](https://github.com/ufs-community/ufs-weather-model/commit/38a29a62461cb1f9bf530420d5bc2f73a4650724) (September 19)
* Update UPP hash to [81b38a8](https://github.com/NOAA-EMC/UPP/commit/81b38a88d860ce7e34e8507c2246151a54d96a39) (August 13)
* All Tier-1 `modulefiles/build_*.lua` files have been updated to use the upp-addon-env spack-stack environment
* `srw_common.lua` was updated to use `g2/3.5.1` and `g2tmpl/1.13.0` (these are required for UPP)
* `.cicd/JENKINSFILE` was updated to replace cheyenne entries with derecho.
* The `doc/tables/Tests.csv` table had nco-mode WE2E tests removed
* The `doc/UsersGuide/CustomizingTheWorkflow/ConfigWorkflow.rst` documentation was updated to updated `ush/config_defaults.yaml` file.
* The `.github/CODEOWNERS` file was updated to add Bruce Kropp to the list of reviewers
* The `exregional_plot_allvars.py` and `exregional_plot_allvars_diff.py` scripts were updated to address changes made to the `postxconfig-NT-fv3lam.txt` file.
* Updated `ush/config_defaults.yaml` to update `PE_MEMBER01` calculation and documentation for `OMP_NUM_THREADS_RUN_FCST` to allow for the `run_fcst` task to properly run on Tier-1 platforms after updates to allow threading to function properly.
* The `ush/machine/*.yaml` files were updated to allow for the `run_fcst` task to properly run on Tier-1 platforms after updates to allow threading to function properly.
* There are not enough resources on Jet to run the high resolution WE2E tests (`136 (ReqNodeNotAvail)`).  Commented out the tests in the `comprehensive.jet` test suite and removed one test from the `coverage.jet` test suite.
* The `ufs-case-studies` WE2E tests are currently failing on Derecho.  The failure is due to the file not being available.  This is an issue because the file in question is named correctly and is available, but the tests fail in the `get_extrn_ics/lbs` tasks stating that the files aren't present.  Commented out these tests in `comprehensive.derecho` and moved WE2E tests to remove from `coverage.derecho`.  Issue #1144 was opened to track this issue on Derecho.

### Type of change
- [X] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
- [X] derecho.intel - Fundamental and Comprehensive WE2E tests were successfully run
- [X] gaea.intel - Fundamental and Comprehensive WE2E tests were successfully run
- [X] hera.gnu - Fundamental and Comprehensive WE2E tests were successfully run
- [X] hera.intel - Fundamental, Comprehensive, AQM WE2E, and AQM sample configuration tests were successfully run
- [X] hercules.intel - Fundamental, Comprehensive, AQM WE2E, and AQM sample configuration tests were successfully run
- [X] jet.intel - Fundamental WE2E tests were successfully run
- [X] orion.intel - Fundamental, Comprehensive, AQM WE2E, and AQM sample configuration tests were successfully run
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [X] fundamental test suite
- [X] comprehensive tests (specify *which* if a subset was used)

## DOCUMENTATION:
Updated documentation related to the table defining the WE2E tests currently available in the SRW App.  The nco-mode WE2E tests had been removed, but were still present in the Tests.csv file.  Removed these entries.  Additional documentation updates were made following updates to the config_defaults.yaml file.

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes

### CODE REVIEW

**Comment by MichaelLueken** [comment]
Please note that I should be able to uncomment out the REFC sections of both `exregional_plot_allvar.py` and `exregional_plot_allvars_diff.py` if I move to using the [postxconfig-NT-rrfs.txt](https://github.com/NOAA-EMC/UPP/blob/develop/parm/postxconfig-NT-rrfs.txt) file in UPP, rather than the [postxconfig-NT-fv3lam.txt](https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/parm/postxconfig-NT-fv3lam.txt) file from the ufs-weather-model.  Moving to this file will require the ability to use the CRTM (satellite radiances are used in this file) and there were issues with the CRTM working on Derecho in the past (please see issue #916).  While it is possible that moving from hpc-stack to spack-stack could have corrected the issue on the machine, it is currently impossible for EPIC to test this.

If another code manager, with an allocation outside of EPIC, is willing to test this capability on Derecho, I can make the necessary changes to use the `postxconfig-NT-rrfs.txt` file and uncomment the REFC entries in the `exregional_plot_allvars.py` and `exregional_plot_allvars_diff.py`.  Thanks.

**Comment by MichaelLueken** [comment]
I was able to successfully find a method to read the composite radar reflectivity from the post GRIB2 file.  The issue was with the pygrib indexing of the GRIB2 file.  Using wgrib2, the 37th entry in the post GRIB2 file was the REFC entry:
```
wgrib2 srw.t00z.prslev.f000.rrfs_conus_25km.grib2 -match REF
37:640531:d=2019070100:REFC:entire atmosphere (considered as a single layer):anl:
```
Using pygrib to generate an index of the GRIB2 file, we see the following for the 37th entry:

`37:5:5 (instant):lambert:atmosphereSingleLayer:level 0 considered as a single layer:fcst time 0 hrs:from 201907010000`

Clearly, there is something going on with the pygrib index.  To get around this issue, I used the rewind() function to move to the start of the index, followed by seek(36), which moves to the 36th entry in the GRIB2 index.  Finally, using readline().values allowed me to read in the information for the 37th (Maximum/Composite radar reflectivity) entry and successfully plot the data.

The following image was generated from the `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot`
 WE2E test using the current develop branch:
FV3_GFS_v17_p8_refc_baseline

This is the image generated using my `feature/hash_update` branch with the changes to `exregional_plot_allvars.py`:
FV3_GFS_v17_p8_refc_hash_update

The issue has been corrected and the composite radar reflectivity has successfully been plotted.

**Comment by MichaelLueken** [comment]
@mkavulich -

While all 6 fundamental WE2E tests successfully pass following the latest updates (example given was run on Hercules):
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              21.74
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               8.50
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              25.67
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024101  COMPLETE              46.18
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241015114  COMPLETE              88.54
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024101511493  COMPLETE              62.54
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             253.17
```
the comprehensive tests are failing with the following error:

`FATAL from PE    15: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic`

It isn't clear what the issue is.  Since the indicated include file is part of the FV3, I'll reach out to them and see what might be happening for the tests that are now failing with this error message.

**Comment by mkavulich** [comment]
@MichaelLueken Thanks for your work on the OMP problem. I came here to report a similar problem: I applied your changes and noticed there is still at least one fundamental test failing on Hera: `grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR`. It's failing with the `not all the pe_end are in the pelist` error, even though all the ufs.configure and other settings appear correct. I can't figure out why as the rest of the fundamental tests are succeeding and only this one is failing, and it's especially worrysome that the failures seem to be different on different platforms. The only thought that immediately comes to mind is maybe there's an off-by-one or similar edge case based on node size?

**Comment by MichaelLueken** [comment]
@mkavulich That could certainly be the issue.  Another potential issue is with respect to `layout` and `io_layout` in the `input.nml` file.  While `layout` is set to be `LAYOUT_X, LAYOUT_Y`, `io_layout` is set to be `1,1`.  Should `IO_LAYOUT_Y` and `IO_LAYOUT_X` be set to `1`, or should the value of `IO_LAYOUT_X` be set to `WRTCMP_write_groups` and `IO_LAYOUT_Y` be set to `WRTCMP_write_tasks_per_group`?  Looking through some of the issues of others who have encountered this error message, it looks like they didn't properly set up one or more of the `layout` and `io_layout` entries in `input.nml`, which is why I'm focusing more on this direction.

**Comment by MichaelLueken** [comment]
Issue [#362](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/362) was opened in NOAA-GFDL/GFDL_atmos_cubed_sphere asking about the strange `FATAL from PE     *: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic` error message.

**Comment by MichaelLueken** [comment]
@mkavulich -

The OMP issue appears to be related to the configuration of the job_card in rocoto.  In order for a WE2E test to properly run the `run_fcst` job, it requires a total number of MPI tasks equal to `OMP_NUM_THREADS_RUN_FCST`*(`LAYOUT_X`*`LAYOUT_Y`+`WRTCMP_write_groups`*`WRTCMP_write_tasks_per_group`).  For the `grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR` WE2E test, `PE_MEMBER01` comes out to be 84 MPI tasks.  This test was failing on Hera because the `run_fcst` job was being submitted to only run with `--ntasks=84`.

For threading purposes, the number of nodes required is equal to the tasks per node (40 on Hera) divided by the number of threads used.  This gives us a `PPN_RUN_FCST` value of 20 (40 tasks per node on Hera/2 threads).  The total number of nodes used is equal to the `PE_MEMBER01`+`PPN_RUN_FCST`-1/`PPN_RUN_FCST`.  This comes out to 84+20-1/20=103/20~5.

While submitting the `run_fcst` job, since there are 40 total tasks per node on Hera and we were calling for only 84 tasks, we were only using 3 nodes, with all 40 tasks per node.  In reality, we required 5 nodes, with 20 tasks per node.  When changing the rocoto XML to use `nodes:` rather than `cores:`, the expected 5 nodes were used and the test successfully passed.  I'm currently running the comprehensive tests on Hera and things are looking good thus far.  Once testing is complete, I'll push the modification and being testing on other machines.

**Comment by MichaelLueken** [comment]
Derecho, Gaea, Hera, and Orion have been successfully updated and tested.  There are still issues with Jet (high resolution tests needing 136 tasks are still in queue) and Hercules (AQM).  Will continue to monitor these two issues tomorrow.

**Comment by MichaelLueken** [comment]
The fundamental, comprehensive, and AQM WE2E tests were run on Tier-1 platforms and successfully pass.

Opening PR for review now.

**Review by rickgrubin-tomorrow — APPROVED** [review]
LGTM

**Review by rickgrubin-noaa — APPROVED** [review]
LGTM

**Review by RatkoVasic-NOAA — APPROVED** [review]
Tested on Hera:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              14.56
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE              12.92
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              29.21
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024103  COMPLETE              47.55
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241031170  COMPLETE              26.38
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024103117095  COMPLETE              51.00
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             181.62
```
Approved.

**Comment by MichaelLueken** [comment]
The Jenkins tests successfully passed for all platforms that they were run on - Derecho, Gaea, Hera GNU, Hera Intel, Jet, and Orion.  The Hercules label was down yesterday, leading to the Jenkins tests skipping Hercules.

Manual runs of the WE2E coverage suite on Hercules have successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
custom_GFDLgrid__GFDLgrid_USE_NUM_CELLS_IN_FILENAMES_eq_FALSE_202  COMPLETE              16.64
grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_202  COMPLETE              15.94
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_202  COMPLETE              69.40
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              25.94
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024110108  COMPLETE              17.88
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20241101081  COMPLETE              47.56
grid_RRFS_NA_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20241101081947  COMPLETE             169.87
grid_SUBCONUS_Ind_3km_ics_NAM_lbcs_NAM_suite_GFS_v16_202411010819  COMPLETE              40.41
MET_verification_only_vx_20241101081948                            COMPLETE               0.36
specify_EXTRN_MDL_SYSBASEDIR_ICS_LBCS_20241101081950               COMPLETE               9.21
2019_hurricane_lorenzo_20241101081950                              COMPLETE              73.14
2020_denver_radiation_inversion_20241101081951                     COMPLETE              72.80
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             559.15
```
Moving forward with merging this PR now.

**Pull request merged**
