### PR TITLE
[develop] Modulefile updates for NOAA Cloud Rocky 8 platforms

### PR DESCRIPTION
**Pull request by natalie-perlin**
## DESCRIPTION OF CHANGES: 
Updated modulefiles o use NOAA Cloud Rocky8 platforms

Files changed:
-modulefiles/build_noaacloud_intel.lua (loading spack-stack procedure change)
-modulefiles/wflow_noaacloud.lua

(!) Note inclusion of loading gnu compiler in build_noaacloud_intel.lua with the successive unloading.
Gnu compiler is required for loading the intel/2023.2.0 module on Rocky8. However, this created a problem when building spack-stack. Unloading the gnu compiler right after the intel module is loaded solves the problem. This approach has been used to build spack-stack-rocky8/spack-stack-1.6.0 as well.

### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update. (possibly an update on configured NOAA Platforms )

## TESTS CONDUCTED: 

- [ ] derecho.intel
- [ ] gaea.intel
- [ ] hera.gnu
- [ ] hera.intel
- [ ] hercules.intel
- [ ] jet.intel
- [ ] orion.intel
- [ ] wcoss2.intel
- [x] NOAA Cloud Azure, fundamental tests are successful, but required many changes to parm/wflow/*.yaml to increase runtime of tasks; changes not included in the PR.
- [x] NOAA Cloud AWS (indicate which platform) - currently running fundamental tests; runtimes of the tasks had to be updated in a way similar to Azure platform
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DOCUMENTATION:
Possibly need documentation updates for NOAA CSPs 

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by natalie-perlin** [comment]
@gspetro-NOAA @christinaholtNOAA - 
ane there a good description of all the tasks and/or metatasks configured or configurable for the SRW runs? 
If the task fails due to hitting the time limit or in need of different node/cpu breakdown, it is not easy to find out what needs to be adjusted, what are all the defaults used for each task if not specified explicitly, and where changes need to be introduced for a particular test.

**Comment by natalie-perlin** [comment]
Fundamental tests successfully completed on Azure Rocky8 with the following timings:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE             360.33
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE              26.01
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE             139.11
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024091  COMPLETE             511.24
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240910210  COMPLETE             149.85
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024091021080  COMPLETE             248.64
```

**Review by RatkoVasic-NOAA — APPROVED** [review]
Looks good to me.

**Comment by natalie-perlin** [comment]
NOAA AWS Rocky fundamental tests complete (with increased times for workflow tasks not included in this PR):

```
All 6 experiments finished
Calculating core-hour usage and printing final summary
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE             139.47
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE              62.33
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE             116.76
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024091  COMPLETE             275.81
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240911165  COMPLETE              82.74
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024091116514  COMPLETE             131.06
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             808.17

Detailed summary written to /contrib/Natalie.Perlin/SRW/expt_dirs/WE2E_summary_20240911201309.txt
```

**Comment by natalie-perlin** [comment]
@MichaelLueken - the changes for CSPs Rocky 8 were merged into the UFS WM, and the WM [Updates for NOAA Cloud Rocky 8 platforms #2436](https://github.com/ufs-community/ufs-weather-model/pull/2436)
 has been closed (merged through [UFS WM PR-2431](https://github.com/ufs-community/ufs-weather-model/pull/2431) )

**Review by MichaelLueken — APPROVED** [review]
@natalie-perlin -

These changes look good to me!  Since these changes are only to The NOAA cloud modulefiles, and the Jenkins tests aren't run on NOAA Cloud (and all of EPIC's cloud compute are currently frozen), I will approve these changes and merge them now.  Thanks!

**Pull request merged**
