### PR TITLE
[develop] Change the build log output file extension from log to txt

### PR DESCRIPTION
**Pull request by BruceKropp-Raytheon**
## DESCRIPTION OF CHANGES: 
When pipeline files are archived to s3 bucket, retrieving the file via a browser attempts to render/display files of known extensions. A browser doesn't generally understand what to do with a .log extension (e.g. build.log). For ease of use in the CI Dashboard, which is a static HTML page, the s3 archived build log needs a .txt extension (e.g. build.txt).

### Type of change
- [X] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
This is CI/CD support, not model or app code. The resulting build log (.txt) was viewed within a browser following manual steps.

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [X] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
would need a pipeline PR build stage (test stage not required) to see that the correct file extension is applied

## DOCUMENTATION:
Any material that mentions the build log filename explicitly, in form of:   srw_build-${PLATFORM}-${COMPILER}.log

## CHECKLIST
- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 
A Code Manager needs to add the following labels to this PR: 
- [X] enhancement
- [X] run_ci

### CODE REVIEW

**Review by JeffBeck-NOAA — APPROVED** [review]

**Review by panll — APPROVED** [review]
Looks good to me.

**Review by MichaelLueken — APPROVED** [review]
@BruceKropp-Raytheon These changes look good to me!

**Comment by MichaelLueken** [comment]
@BruceKropp-Raytheon Due to the current communication issue between Jenkins and Jet, the Jet tests were aborted (why the `continuous-integration/jenkins/pr-merge` is showing that the commit was aborted).  Visual inspection of the Jenkins tests show that the tests successfully completed - https://jenkins.epic.oarcloud.noaa.gov/blue/organizations/jenkins/ufs-srweather-app%2Fpipeline/detail/PR-690/1/pipeline.

However, I've noticed some weird behavior with the Publish artifacts to S3 Bucket entries for both Build and Test.  It reports that access is denied and fails to push the artifacts to the S3 bucket:

```
ERROR: Failed to upload files

com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied
```

Also, I'm not seeing the generation of a srw_build-${PLATFORM}-${COMPILER}.txt file or it's inclusion in the S3 bucket.  I just want to make sure that everything looks correct on your end before merging this work in.  Thanks!

**Comment by MichaelLueken** [comment]
@BruceKropp-Raytheon I have merged @kbooker79's PR to update the path to the S3 bucket to the OAR account.  Once you have merged the latest develop into your branch and corrected the conflicts, I will be able to move forward with these changes.  Thanks!

**Comment by MichaelLueken** [comment]
@BruceKropp-Raytheon Is there a specific reason that you closed this PR and opened PR #706?  Since the approvals have been given and testing completed in this PR, it would be best to continue within this PR rather than open a new one.  Please close PR #706 and reopen this PR, and I can move forward with merging this work.  Please let me know if there are issues with doing so.  Thank you very much.

**Comment by MichaelLueken** [comment]
Reopening previously reviewed PR.  So long as the necessary changes are available, will merge this work into develop.

**Comment by MichaelLueken** [comment]
@BruceKropp-Raytheon The changes in this PR are identical to those in PR #706.  I will move forward with merging these changes to develop now.  Thank you very much!

**Pull request merged**
