### PR TITLE
Add inline post option to the SRW App

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
- Add a compile argument for inline post to the ufs weather model in 'src/CMakeLists.txt'.
- Update some modules in 'env' for Hera and WCOSS Dell to the latest.

## TESTS CONDUCTED: 
- GST test + verification on Hera and WCOSS Dell.
- New WE2E test for inline post on Hera and WCOSS Dell.

## ISSUE: 
- Fixes issue mentioned in #149.
- Fixes issue mentioned in https://github.com/NOAA-EMC/regional_workflow/issues/511

### CODE REVIEW

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, please review this PR. Since the pr for inline post was merged in the regional workflow, this pr should be merged to run the latest regional workflow correctly.

**Comment by JeffBeck-NOAA** [comment]
@chan-hoo, do environment files for all other systems (aside from Hera and WCOSS) need to be updated to work with in-line post?

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, No, they don't. I updated the env files for Hera and WCOSS because I got a version change notice when I compiled the SRW App on them. These are not related to the inline post.

**Comment by JeffBeck-NOAA** [comment]
OK, thanks!  Approving.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
