### PR TITLE
[develop]: Add debugging guide to README.md

### PR DESCRIPTION
**Pull request by MichaelLueken**
## DESCRIPTION OF CHANGES: 
Ben Brinkley, from EPIC's ECE team, has requested that the link to EPIC's debugging guide be added to the `README.md` file.  This PR adds this link to the `README.md` file.

### Type of change
- [X] This change is a documentation update to the `README.md` file.

## TESTS CONDUCTED: 
None required

## CHECKLIST
- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## CONTRIBUTORS (optional): 
Ben Brinkley and EPIC ECE team.

### CODE REVIEW

**Comment by MichaelLueken** [comment]
Closing PR.  Need PDF file to be available outside of NOAA-centric Google Doc.

**Comment by MichaelLueken** [comment]
The EPIC ECE team has hosted their Debugging Guide on the EPIC web site.  This version is now being linked in the updated `README.md` file.  Please take a moment and look at the change and approve if you are okay with it.  Thanks!

**Review by natalie-perlin — APPROVED** [review]
Looks good!!

**Review by gspetro-NOAA — APPROVED** [review]
Agreed--looks good!

**Pull request merged**
