### PR TITLE
[develop] Change settings for AQM to meet NCO requirement and improve near-real-time runs

### LINKED ISSUE #662: Some setting for AQM needs to be changed to meet NCO requirement
## Description
- Some setting for AQM (Online-CMAQ) needs to be changed to meet the NCO's requirement and improve the result.

## Acceptance Criteria (Definition of Done)
- The sample scripts for AQM run successfully.

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
Some settings for air quality modeling (Online-CMAQ) are changed to meet the NCO's requirement and improve the results.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- Sample scripts for AQM on Hera and WCOSS2
- WE2E test on Hera
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16

- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 
Fixes issue mentioned in #662 

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## CONTRIBUTORS: 
@JianpingHuang-NOAA

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@chan-hoo Overall, these changes look good to me!

I take it that the changes made to `parm/FV3.input.yml` improve the results.  Was there an increase in wall time with these modifications, or were the modifications such that there is no discernible difference?

**Review by danielabdi-noaa — APPROVED** [review]
LGTM

**Comment by chan-hoo** [comment]
@MichaelLueken, @danielabdi-noaa, thank you for your approval! @JianpingHuang-NOAA, can you answer @MichaelLueken 's questions?

**Comment by JianpingHuang-NOAA** [comment]
@MichaelLueken @chan-hoo 

The change of k_split and n_split number with parm/FV3.input.yml  has improved the forecast model running time and does not affect the results.  The change has been used in our retro runs ( 9 months in total) and near real-time testing. The code with the change has been running very stable.

**Comment by MichaelLueken** [comment]
@chan-hoo All of the Jenkins tests successfully ran through to completion and passed.  The `Pending` message for `Build and Test` is likely due to the length of time it took the Gaea test to complete.  The allocation of the `nggps_emc` account on the machine has been fully used, so the tests are running in windfall.  Following the SRW code management meeting this afternoon, I will merge this work into develop (one of the topics of discussion is the order of merging current PRs).

@JianpingHuang-NOAA Thank you very much for specifying the changes made to the parm/FV3.input.yml file!  Since it improves the run time and doesn't affect results, I'm perfectly fine with moving forward with these changes.

**Pull request merged**
