### PR TITLE
Replace deprecated NCAR python environment with conda on Cheyenne

### PR DESCRIPTION
**Pull request by mkavulich**
## DESCRIPTION OF CHANGES: 
The `ncar_pylib` application is scheduled for decommissioning on Cheyenne in the coming months (see deprecation notice at https://arc.ucar.edu/knowledge_base/70549906), and the recommended replacement for managing python environments is conda. Fortunately this will allow us to bring Cheyenne in line with other platforms that are already using conda. 

I have created a conda environment containing the needed python packages for running the UFS SRW workflow at `/glade/p/ral/jntp/UFS_SRW_app/conda/regional_workflow`. This PR modifies the `wflow_cheyenne` module to use this new conda environment. Also took the opportunity to update and correct the module description.

Additionally, I created a `/glade/p/ral/jntp/UFS_SRW_app/conda/python_graphics` conda environment for use with python graphics, and updated the Users Guide to reflect this change. No code changes are necessary for this portion of the PR however; that will be handled in regional_workflow.

## TESTS CONDUCTED: 
**Important note**
*These tests were run with a modified srw_common module to remove ncio; this is causing build problems on Cheyenne, but is only needed for GSI so can be safely removed for these tests. See #325 for more info.* 

Ran the proposed "fundamental" test suite (see #277) for both Intel and Gnu on Cheyenne; all tests passed except for `specify_DOT_OR_USCORE` with GNU; this should not be related to these changes but I will investigate regardless.
(Edit: This same failure occurs in develop branch; see https://github.com/ufs-community/regional_workflow/issues/808)

These changes only impact Cheyenne-specific files, so no tests on other platforms should be necessary. However, I will run one of the automated test suites for safety's sake.

Did not run any tests for the python graphics except to ensure that the proper packages were available; more thorough testing will be handled in a forthcoming regional_workflow PR.

## DEPENDENCIES:
 - [RW #812](https://github.com/ufs-community/regional_workflow/pull/812)

## DOCUMENTATION:
Updated python graphics environment documentation for new conda environment.

### CODE REVIEW

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/989669228/20220707052015/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
Experiment Succeeded on hera: nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR
All experiments completed

**Review by natalie-perlin — APPROVED** [review]

**Comment by gsketefian** [comment]
@mkavulich I'm trying to run the fundamental test set on Cheyenne (using intel to begin with) with `run_WE2E_tests.sh` but am getting this error:
```
  Error: python module yaml not available
```
Here is more detail on what I did:
1) Build the App using `> ./devbuild.sh --platform=cheyenne`
2) Load the appropriate workflow environment:
```
> module use -a /glade/scratch/ketefian/TEST_mike_pr326/ufs-srweather-app/modulefiles
> module load wflow_cheyenne
> conda activate /glade/p/ral/jntp/UFS_SRW_app/conda/regional_workflow
```
3) Create the file `my_tests.txt` under `regional_workflow/tests/WE2E` that contains the list of fundamental tests.
4) Run the tests:
```
> ./run_WE2E_tests.sh tests_file=my_tests.txt machine=cheyenne generate_csv_file="FALSE" account=P48503002 expt_basedir="intel_01"
```
This then gives me the yaml error above:
```
...
========================================================================
========================================================================

Starting experiment generation...

========================================================================
========================================================================

  Error: python module yaml not available

ERROR:
  From function:  "generate_FV3LAM_wflow"
  In file:  "generate_FV3LAM_wflow.sh"
  Full path to file:  "/glade/scratch/ketefian/TEST_mike_pr326/ufs-srweather-app/regional_workflow/ush/generate_FV3LAM_wflow.sh"
  Errors found: check your python environment
  
  Instructions for setting up python environments can be found on the web:
  https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started


Exiting with nonzero status.
...
```
Did I miss a step somewhere?  Thanks.

**Comment by mkavulich** [comment]
@gsketefian I'm not sure why this was even working for me in my original tests, but it seems like I forgot to include the `pyyaml` package. I have updated the `/glade/p/ral/jntp/UFS_SRW_app/conda/regional_workflow` conda environment to include the necessary package, can you try again and let me know the results?

**Comment by gsketefian** [comment]
@mkavulich I retested and the `run_WE2E_tests.sh` script worked, but most of the fundamental tests failed.  The error still seems to be related to a missing yaml module.  I checked the log files of a couple of the tests and they fail in the `get_extrn_[ics|lbcs]` tasks.  I assume the rest are the same.  The error is this:
```
ModuleNotFoundError: No module named 'yaml'
```
For example, look in this log file:
`/glade/scratch/ketefian/TEST_mike_pr326/expt_dirs/intel_02/grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_HRRR/log/get_extrn_ics_2020081000.log`
Let me know what you think.  Thanks.

**Comment by mkavulich** [comment]
@gsketefian This is concerning, I am still unable to replicate the problems you are seeing. I worry that this may be shell-related, you are using csh correct?

**Comment by gsketefian** [comment]
> @gsketefian This is concerning, I am still unable to replicate the problems you are seeing. I worry that this may be shell-related, you are using csh correct?

Yes, using csh.  I switched to csh from bash a while ago to test Jamie's csh issues, and I forgot to switch back.  I guess that's a good thing in this situation.

Let me know if there's anything you want me to try.

**Comment by mkavulich** [comment]
@gsketefian I have another potential fix...can you run `conda init` with the conda module loaded, then try again? This may be a one-time step that is required for setting up the user's .bashrc/.tcshrc for conda to work correctly with batch jobs and subshells.

If this works I'll probably have to add this command to the print statement from the modulefile; if it has already been done the command has no effect so there's no harm in making users run it every time to be safe.

**Comment by christinaholtNOAA** [comment]
Is this not a run-time issue? There's a possibility that you will also want to change the regional_workflow modulefiles to be consistent with this new update.

**Comment by mkavulich** [comment]
That's a good point @christinaholtNOAA; I'm still not sure why the tests are working for me and not Gerard, but I should make that update and see if that fixes the issue.

**Comment by gsketefian** [comment]
@mkavulich Please just let me know when it's ready to retest.  Thanks.

**Comment by mkavulich** [comment]
Okay @gsketefian one more time: I had to make some changes to regional_workflow as well, so can you try by updating to the branch in my fork of regional_workflow I just pushed to Externals.cfg? You shouldn't need to re-build the executables, just delete regional_workflow and check out the new version to try again.

If this works, the regional_workflow PR will need to be merged before this one: https://github.com/ufs-community/regional_workflow/pull/812

**Comment by willmayfield** [comment]
@mkavulich I tried it with your regional_workflow fixes, and tried doing conda init as you said, but still getting the missing yaml module error.

I added a "conda activate /glade/p/ral/jntp/UFS_SRW_app/conda/regional_workflow" to load_modules_run_task.sh outside of the clause where it does conda activate $SRW_ENV, and now the tests succeed. So, either SRW_ENV isn't being set or isn't being propagated somewhere for me.

**Comment by christinaholtNOAA** [comment]
I noticed that in the regional_workflow module `conda_regional_workflow` it uses `module load conda` instead of `module load conda/latest` like several others. Is there a possibility that the module isn't being loaded correctly in the regional_workflow?

**Comment by gsketefian** [comment]
@mkavulich I just got your latest `ufs-srweather-app` branch and cloned the `regional_workflow` that it specifies.  I retried running one test but unfortunately I'm getting the same error:
```
ModuleNotFoundError: No module named 'yaml'
```
This is in `get_extrn_[ics|lbcs].log`.  My experiment directory is:
```
/glade/scratch/ketefian/TEST_mike_pr326/expt_dirs/intel_03/grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
```
Let me know if you want me to try any debugging.

**Comment by gsketefian** [comment]
@mkavulich I'm rerunning the test `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16` and it seems to be working.  Assuming it succeeds, would you like me to test all the fundamental tests?

**Comment by mkavulich** [comment]
@gsketefian That would be great! There are a few known failures on Cheyenne but I can sort those out later.

**Comment by gsketefian** [comment]
@mkavulich Ok.  That single test passed, now I'm running the full fundamental set.

**Comment by gsketefian** [comment]
@mkavulich All the fundamental tests passed on Cheyenne (using Intel compiler).  Below is the full list for reference.  Approving.
```
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta
grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_HRRR
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
community_ensemble_2mems
custom_ESGgrid
deactivate_tasks
inline_post
MET_ensemble_verification
MET_verification
nco_ensemble
pregen_grid_orog_sfc_climo
specify_DOT_OR_USCORE
specify_DT_ATMOS_LAYOUT_XY_BLOCKSIZE
specify_RESTART_INTERVAL
specify_template_filenames
```

**Review by gsketefian — APPROVED** [review]

**Review by panll — APPROVED** [review]

**Comment by mkavulich** [comment]
Updated RW hash to include those changes, tests ran successfully again. Merging.

**Pull request merged**
