### PR TITLE
[develop] Adding mixed-layer convective available potential energy (MLCAPE) to the verification

### PR DESCRIPTION
**Pull request by panll**
## DESCRIPTION OF CHANGES: 
Adding MLCAPE to the verification configure files:
metplus/PointStat_conus_sfc.conf
metplus/PointStat_upper_air.conf

### Type of change

- [x] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
Tested on Hera.

- [ x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
N/A

## ISSUE: 

N/A

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [x ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
Thanks for getting this incorporated and tested, @linlin-pan!

**Review by JeffBeck-NOAA — APPROVED** [review]
@linlin-pan, thanks for getting MLCAPE incorporated and tested in the SRW App verification task!

**Comment by gsketefian** [comment]
@panll Is there any way to check whether the METplus output is reasonable?

**Comment by panll** [comment]
> @panll Is there any way to check whether the METplus output is reasonable?

It can be verified by online sounding or other outputs (e.g., SHARPpy outputs) @gsketefian

**Comment by MichaelLueken** [comment]
@panll The two bug fixes that were merged into develop this morning include updates to the `.cicd/Jenkinsfile` that will be required before I can launch the Jenkins test for this PR.  At your earliest convenience, please merge these two updates into your fork's `develop` branch.  Thank you very much!

**Comment by panll** [comment]
> @panll The two bug fixes that were merged into develop this morning include updates to the `.cicd/Jenkinsfile` that will be required before I can launch the Jenkins test for this PR. At your earliest convenience, please merge these two updates into your fork's `develop` branch. Thank you very much!

Updated. Please let me know if anything else is needed, thanks! @MichaelLueken

**Review by gsketefian — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@panll I was able to run the `MET_verification` and saw `MLCAPE` in the final `STATS` files.  Approving this work.

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/1239617486/20230215185019/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE
Experiment Succeeded on hera: community_ensemble_2mems_stoch
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: pregen_grid_orog_sfc_climo
Experiment Succeeded on hera: pregen_grid_orog_sfc_climo
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2
Experiment Succeeded on hera: grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
Experiment Succeeded on hera: community_ensemble_2mems_stoch
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
Experiment Succeeded on hera: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
Experiment Succeeded on hera: MET_ensemble_verification
Experiment Succeeded on hera: MET_ensemble_verification
All experiments completed

**Pull request merged**
