### PR TITLE
[develop] Add RAVE data processing to fire_emission task for AQM 

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
In the current workflow for AQM (Online-CMAQ), there are two options for the `fire_emission` task: 1) copy from the custom directory, and 2) retrieve from HPSS. The files on HPSS have been generated by a separate data processing task. In this PR, the data processing task for the RAVE fire emission file is incorporated into the UFS SRW App. 
In addition, the file existence check for the GEFS aerosol data files is added to the `aqm_lbcs' task.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 
Fixes issue mentioned in https://github.com/NOAA-EMC/AQM/issues/62

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## CONTRIBUTORS: 
@KaiWang-NOAA

### CODE REVIEW

**Review by MichaelLueken — COMMENTED** [review]
@chan-hoo Since you have already updated the `AQM_utils` hash in `Externals.cfg`, would it be possible to also update the `UPP` hash to `2b2c84a`?

While updating the ufs-weather-model hash to `84b28ec` at [d036849](https://github.com/ufs-community/ufs-srweather-app/commit/d03684908562a7118f9c369852cdfe2b66371977), the `UPP` hash that is used with that version of the weather model is `2b2c84a`.  However, the `UPP` hash wasn't updated in the SRW App.

If you would prefer, I can add it to your branch, or I can create a new PR to align the UPP hash with what the weather model is using.  Please let me know how you would like to move forward with this.

Thanks!

**Comment by chan-hoo** [comment]
@MichaelLueken, sure. I'll update it now.

**Comment by MichaelLueken** [comment]
Thank you very much, @chan-hoo!

**Review by MichaelLueken — APPROVED** [review]
@chan-hoo These changes look good to me!  I also see from [NOAA-EMC/AQM#62](https://github.com/NOAA-EMC/AQM/issues/62) that Kai has tested this update for four cycles and the workflow reproduces identical RAVE fire emissions, so I'll go ahead and approve these changes.

**Comment by chan-hoo** [comment]
@MichaelLueken, thank you!

**Review by danielabdi-noaa — APPROVED** [review]
@chan-hoo I have run the `aqm_community_aqmna13` test case successfully on Hera so approving.

**Comment by chan-hoo** [comment]
@danielabdi-noaa, thank you!

**Comment by chan-hoo** [comment]
@MichaelLueken, since this PR has passed all the four tests and got two approvals, I'll merge this. I need this PR for my next task.

**Pull request merged**
