### PR TITLE
[production/AQM.v7] Merge the changes to address NCO's review comments on AQMv7 delivery package partly

### PR DESCRIPTION
**Pull request by JianpingHuang-NOAA**
This PR is used to address Issue 964  (https://github.com/ufs-community/ufs-srweather-app/issues/964) partly

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- [ ] hera.intel
- [ ] orion.intel
- [ ] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [x] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 
- [ ] Work In Progress
- [ ] bug
- [x] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, please do not remove anything in `manage_externals`. I'll move it on my end.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, why do you delete the input files for FV3_GFS_v16 such as diag_table and field_table in the `parm` directory? How does your NRT run without those files?

**Comment by JianpingHuang-NOAA** [comment]
Yes, I only keep those related aqm.  I did not find any impact on our model running and results. I have completed the tests

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, which CCPP physics suite are you using in your NRT?

**Comment by JianpingHuang-NOAA** [comment]
> @JianpingHuang-NOAA, please do not remove anything in `manage_externals`. I'll move it on my end.

I deleted "test" subdirectory only under ~/manage_external.  I am not comfortable with other changes. So I leave them for you.

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I can see the files in your branch, but the PR is saying they are deleted. Strange ....

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA, I got it now. They have different names for AQM. Sorry. I was confused. Approving now.

**Review by chan-hoo — APPROVED** [review]

**Pull request merged**
