### PR TITLE
Update manage_externals for Python 3+ bug fix, support for 3.7 and 3.8

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
Updates manage_externals to the most recent release which includes a critical Python 3+ bug fix and supports 3.7 and 3.8.  This new version avoids the previous incompatibility between manage_externals and the YAML namelist generation/Jinja templating for XML and diag_table files.  Users will no longer have to load different versions of Python in-between manage_externals and running the workflow.

## TESTS CONDUCTED: 
Tested successfully on Hera.  All repos are cloned correctly.  @JulieSchramm tested on Cheyenne.

### CODE REVIEW

**Comment by JulieSchramm** [comment]
I still need to run

ncar_pylib /glade/p/ral/jntp/UFS_CAM/ncar_pylib_20200427

on Cheyenne to generate the workflow.  Is this expected behavior?

**Comment by JeffBeck-NOAA** [comment]
@JulieSchramm If that Cheyenne command is to load a version of Python for both manage_externals and the workflow, then yes, that's still required.

**Comment by JulieSchramm** [comment]
I can run manage_externals without the ncar_pylib command and it works
fine, then I need the ncar_pylib command to run ./generate_FV3SAR_wflow.sh,
as we were doing before this PR.

**Comment by JeffBeck-NOAA** [comment]
@JulieSchramm That sounds like normal behavior.  Did you previously need the "ncar_pylib" command for manage_externals?  The Python version required for the generate script may not be the default on Cheyenne, and may still require you to run the ncar_pylib command.

**Comment by JulieSchramm** [comment]
I didn't need the ncar_pylib command previously to run manage_externals.

**Comment by JeffBeck-NOAA** [comment]
@JulieSchramm OK, then everything is working as expected.  Thanks for testing!

**Pull request merged**
