### PR TITLE
[develop] Fix plotting bug.

### LINKED ISSUE #527: Plot_allvars task goes DEAD due to case mismatch
## Expected behavior
The plotting scripts should run successfully as part of the workflow. The plotting tasks are based on the original functional plotting scripts, and since the addition of the plotting scripts to the workflow, it seems that no one else has encountered issues. 

## Current behavior
On Hera, I get an error when trying to run the plotting tasks on the "out-of-the-box" case (25km CONUS grid, FV3_GFS_v16 physics, DATE_FIRST_CYCL: 2019061518, FCST_LEN_HRS: 12). `exregional_plot_allvars.py` cannot open the files in `postprd` due to a case mismatch. The files in `postprd` are named like `rrfs.t18z.prslev.f***.RRFS_CONUS_25km.grib2`, but the `plot_allvars` task is trying to open a file named `rrfs.t18z.prslev.f***.rrfs_conus_25km.grib2`. (See image below.) 

PlotError

## Machines affected
Hera/intel
Possibly others, but I have only tested on Hera.

## Steps To Reproduce
Here is my `config.yaml` file:
config_file
I generated the workflow and waited for it to terminate as usual, but the task went DEAD. The error message from the log is in the section above. 

## Detailed Description of Fix
Removing `.lower()` from line 345 of `exregional_plot_allvars.py` and line 355 of `exregional_plot_allvars_diff.py` fixed the issue for me. (These are the lines that set `POST_OUTPUT_DOMAIN_NAME`.) After removing `.lower()` in those two places, I successfully ran the experiment using the same config file (except for the EXPT_SUBDIR field). 

However, I am surprised that this hasn't caused problems sooner since the `.lower()` syntax was in the original plotting script. I am hoping others can verify whether the current code has this issue (and whether the fix works) on other systems/with other experiments.

### PR DESCRIPTION
**Pull request by danielabdi-noaa**
## DESCRIPTION OF CHANGES: 

Fixes issue #527. The fix is applied to `setup.py` by updating the dictionary value of `POST_OUTPUT_DOMAIN_NAME` to be lowercase. Currently an uppercase name is writtern to `var_defns.sh` which is what is causing the problem. It was also possible to fix it by modifying the plotting scripts not to change cases, but I think grib file names with all lowercase letters is desirable so I decided to change `setup.py` instead.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [X] hera.intel
   grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 

- #527 

## CHECKLIST

- [X] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@danielabdi-noaa Thanks for addressing the plotting task issue so quickly!  I have been able to run the `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional_plot` test on Jet and Hera without issue.  Do you think it would be a good idea to add this test to one of the fundamental test suites to ensure that this doesn't happen again?

**Comment by danielabdi-noaa** [comment]
@MichaelLueken Good idea. I think the `fundamental.hera.intel.nco` has the same test case without plotting so we can replace that with the one that does plotting. It will be testing it in NCO mode though, which should work but probably better to test community mode instead. Or we can add the "community" version of the plotting to some other machine that is not doing a lot of work or modify an existing test case to do plotting without adding a new one.

**Comment by MichaelLueken** [comment]
@danielabdi-noaa Could we remove the non-plotting test from `fundamental.hera.intel.nco` and add the plotting test to `fundamental.hera.gnu.com`?  This way, the test is still being done on Hera and with the "community" version.

**Comment by danielabdi-noaa** [comment]
@MichaelLueken Yes, as it turns out the GNU fundamental test on hera also had that test case so I changed both to test `_plot` test case so that we test plotting both in community and nco modes.

**Comment by MichaelLueken** [comment]
@danielabdi-noaa Great!  I have gone ahead and submitted the Jenkins tests.

**Review by gspetro-NOAA — APPROVED** [review]
The plotting runs without a glitch on Jet and AWS!

**Pull request merged**
