### PR TITLE
Add more documentation

### PR DESCRIPTION
**Pull request by JulieSchramm**
View at: https://srw-app-jls.readthedocs.io/en/feature-config_new_platform/

- Add 5 questions and answers to FAQ chapter
- Add placeholder for ConfigWorkflow chapter
- Add LAM Domains chapter plus three figures
- Fix typos in SRW App Overview chapter
- Add placeholder for ConfigNewPlatform chapter with system requirements section
- Add new files to index.rst and rearrange order of some chapters

Both html, pdf and readthedocs builds succeed.

### CODE REVIEW

**Comment by jwolff-ncar** [comment]
@JulieSchramm Will you add in the updates to the LAM grids chapter from Gerard/Jeff yesterday into this PR before merging?

**Comment by jwolff-ncar** [comment]
All looks good at this point. Will you continue to update this PR with additional files or do you want this one approved and then to open new PRs as documentation updates continue?

**Comment by JulieSchramm** [comment]
Can you approve it so I can open a new PR for the next chapter?

**Comment by JeffBeck-NOAA** [comment]
> Can you approve it so I can open a new PR for the next chapter?

@JulieSchramm, @jwolff-ncar's on PTO today, so I'll go ahead and approve based on your conversation.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
