### PR TITLE
[develop] Updated cheyenne configs to use new CMAQ shared conda env for tier-1 platforms.

### LINKED ISSUE #684: [develop] Update CMAQ task configs to use new shared conda configs on tier-1 platforms
## Description
Natalie Perlin created a new shared conda config to support CMAQ users on on Tier-1 platforms (Hera, Orion, Gaea, Jet, Cheyenne). This new environment is named 'regional_workflow_cmaq', and includes netcdf4 and dependencies (xarray, numpy, scipy). The task module configs for CMAQ in ufs_wrweather_app/modulefiles/tasks/HOST/ can now be updated to load this shared config when the tasks are run.

## Solution
For each host, create a .lua file to load the 'regional_workflow_cmaq', and load that module for any tasks requiring the additional python modules. For example, on cheyenne we now have ufs_wrweather_app/modulefiles/tasks/cheyenne/miniconda_regional_workflow_cmaq.lua:
```
unload("python")
prepend_path("MODULEPATH","/glade/work/epicufsrt/contrib/miniconda3/modulefiles"
)
load(pathJoin("miniconda3", os.getenv("miniconda3_ver") or "4.12.0"))

setenv("SRW_ENV", "regional_workflow_cmaq")
```

And for the fire_emission task, we now have ufs_wrweather_app/modulefiles/tasks/cheyenne/fire_emission.local.lua:
```
load("ncarenv")
load("miniconda_regional_workflow_cmaq")
```

## Alternatives
Alternatively, users can use a non-shared environment with the required python packages, and maintain their own local task scripts to manage configuration for tasks at runtime.

## Related to
https://github.com/ufs-community/ufs-srweather-app/pull/656

### PR DESCRIPTION
**Pull request by padhrigmccarthy**
## DESCRIPTION OF CHANGES: 
Implemented config changes for SRW CMAQ users on cheyenne. These changes load the new shared conda environment 'regional_workflow_cmaq' for tasks that require the netcdf4 python package and its dependencies. This update saves each individual user from having to create the appropriate conda environment to run CMAQ. This should be a non-breaking change for non-CMAQ users, and for all non-cheyenne users. Similar config changes will be required on the other tier-1 platforms.

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
- [ ] hera.intel
- [ ] orion.intel
- [x ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## DEPENDENCIES:
None.

## ISSUE: 
https://github.com/ufs-community/ufs-srweather-app/issues/684

## CHECKLIST
- [x ] My code follows the style guidelines in the Contributor's Guide
- [ x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 
A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

## CONTRIBUTORS (optional): 
Natalie Perlin created the shared conda environments on the tier-1 platforms. Chan-Hoo Jeon consulted on the overall approach.

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@padhrigmccarthy These changes are specific to cleaning up the Cheyenne task modulefiles and replacing `miniconda_regional_workflow-cmaq` with the newly created `miniconda_regional_workflow_cmaq` conda environment.  These changes look good to me!

**Comment by mkavulich** [comment]
@padhrigmccarthy I don't see any problem with these changes, but I was unable to build the AQM app on Cheyenne using the [instructions in the users guide](https://ufs-srweather-app.readthedocs.io/en/develop/AQM.html). The `devbuild.sh` script is looking for a UFS_UTILS module that does not exist:

```./devbuild.sh -p=cheyenne -a=ATMAQ
PLATFORM(MACHINE)=cheyenne
COMPILER=intel
MODULE_FILE=build_cheyenne_intel
cp: cannot stat '/glade/scratch/kavulich/workdir/UFS/PR_685/ufs-srweather-app/sorc/UFS_UTILS/modulefiles/build.cheyenne.intel.lua': No such file or directory
ls /glade/scratch/kavulich/workdir/UFS/PR_685/ufs-srweather-app/sorc/UFS_UTILS/modulefiles/
build.cheyenne.intel  build.hera.gnu.lua    build.jet.intel.lua  build.orion.intel.lua  build.stampede.intel
build.gaea.intel      build.hera.intel.lua  build.odin.intel     build.s4.intel.lua     build.wcoss2.intel.lua
```

I'm not sure why the UFS_UTILS modulefiles are not consistently named across platforms. It seems like there will be the same issue with UPP as well.

I was able to build successfully by manually modifying for the correct paths, but it seems like this will need to be addressed eventually (not sure if it needs to be changed in the script or in those repositories).

**Comment by padhrigmccarthy** [comment]
@mkavulich - Thanks. This build failure is due to the fact that the hashes for UFS_UTILS on [develop] predate the configs I contributed for cheyenne. I was planning to update the docs once we get this all running with the new configs and the shared regional_workflow_cmaq conda env, including instructions for changing the hashes in Externals.cfg. But I'm waiting for this merge to complete so I can put the correct hash for CMAQ in the instructions as well! I think there may end up being platform-specific instructions required, so that will require some discussion.

**Review by mkavulich — APPROVED** [review]

**Comment by MichaelLueken** [comment]
@padhrigmccarthy All automated Jenkins testing has passed, with the exception of Gaea.  Gaea went down for maintenance yesterday and the `grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR` test hadn't finished before going down.  Ultimately, the Gaea test was automatically aborted.  Gaea is still down this morning (I'm unable to connect to the machine and Jenkins reports it is still down).

Since the rest of the tests pass, I will not hold this update back.

**Pull request merged**
