### PR TITLE
[develop] Add a WE2E test for AQM

### LINKED ISSUE #815: WE2E test for AQM is necessary
## Description
A WE2E test for Air Quality Modeling (AQM) does not exist in the app. To prevent any unexpected issue on AQM, a new WE2E test for AQM is necessary.

## Solution
A WE2E test for AQM is added to the app.

## Acceptance Criteria (Definition of Done)
A new WE2E test is completed successfully on Hera

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
- Add a WE2E test for AQM (community mode).
- It works on Hera and WCOSS2.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 
1. Build the app for AQM: `./devbuild.sh -p=hera -a=ATMAQ`
2. Run the WE2E test for AQM: `aqm_grid_AQM_NA13km_suite_GFS_v16`
- [x] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 
Fixes issue mentioned in #815 

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## CONTRIBUTORS: 
@natalie-perlin

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Review by JeffBeck-NOAA — APPROVED** [review]

**Review by MichaelLueken — APPROVED** [review]
@chan-hoo I was able to successfully run the new WE2E test for AQM on Hera:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
aqm_grid_AQM_NA13km_suite_GFS_v16                                  COMPLETE             981.50
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             981.50
```

Approving this PR now.

**Comment by chan-hoo** [comment]
@RatkoVasic-NOAA, @JeffBeck-NOAA, @MichaelLueken, thank you for your approvals !!!

**Comment by MichaelLueken** [comment]
@chan-hoo The automated Jenkins tests passed on Cheyenne, Hera, and Jet.  The coverage WE2E tests were manually ran on Orion and all successfully passed:

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
deactivate_tasks                                                   COMPLETE               1.20
get_from_AWS_ics_GEFS_lbcs_GEFS_fmt_grib2_2022040400_ensemble_2me  COMPLETE             753.35
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta   COMPLETE             254.86
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot        COMPLETE             140.57
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta            COMPLETE              14.14
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp  COMPLETE               9.55
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR              COMPLETE             379.63
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16   COMPLETE              27.05
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16    COMPLETE             277.57
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0         COMPLETE              13.15
nco                                                                COMPLETE               7.57
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1878.64
```
Now moving forward with merging this work.

**Comment by christinaholtNOAA** [comment]
I didn't see this before it got merged but I wanted to say this is a great addition! Thanks @chan-hoo!

**Pull request merged**
