### PR TITLE
[develop] Update nco version

### LINKED ISSUE #1076: Fix nco version for Hera/Intel
## Expected behavior
For some reason Hera with Intel compiler was using system installed nco library (4.9.3 version). It was not noticed until sys admins removed read permissions to 4.9.3 version and installed new version (5.1.6).
```
Hera:/apps/modules/modulefiles/nco>ll
-rwx------ 1 root root  651 Sep 08 2023 21:17:20 4.9.3
-rw-r--r-- 1 root root 1356 Feb 29 2024 17:21:01 5.1.6
```
All other machines/compilers use spack-stack installed nco@5.0.6

## Current behavior
Load in modules fail because of wrong nco version (for Hera with Intel compiler).

## Machines affected
Hera / Intel

## Steps To Reproduce
1. Clone ufs-srw-app
2. cd ufs-srw-app
3. module use $PWD/modulefiles
4. module load build_hera_intel

## Detailed Description of Fix (optional)
Replacing version 4.9.3 with 5.0.6 (spack-stack installation)

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
## DESCRIPTION OF CHANGES: 
Hera with Intel compiler was using system installed nco library (4.9.3 version). It was not noticed until sys admins removed read permissions to 4.9.3 version and installed new version (5.1.6).
```
Hera:/apps/modules/modulefiles/nco>ll
-rwx------ 1 root root  651 Sep 08 2023 21:17:20 4.9.3
-rw-r--r-- 1 root root 1356 Feb 29 2024 17:21:01 5.1.6
```
Will use spack-stack installed nco (version 5.0.6), like all other machines/compilers.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## TESTS CONDUCTED: 

- [x] hera.intel
- [ ] orion.intel
- [ ] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 
https://github.com/ufs-community/ufs-srweather-app/issues/1076

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [x] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [x] high priority
- [x] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Comment by RatkoVasic-NOAA** [comment]
```
All 6 experiments finished
Calculating core-hour usage and printing final summary
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              10.01
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               6.81
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              14.62
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024042  COMPLETE              34.06
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240423013  COMPLETE              23.30
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024042301381  COMPLETE              22.14
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             110.94
```

**Review by chan-hoo — APPROVED** [review]

**Review by christinaholtNOAA — APPROVED** [review]
I just discovered that this change is required. Thanks for opening the PR, @RatkoVasic-NOAA!

**Review by MichaelLueken — APPROVED** [review]
@RatkoVasic-NOAA -

These changes look good to me and the fundamental tests successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE               8.93
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               5.75
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              13.79
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024042  COMPLETE              34.47
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240423132  COMPLETE              22.59
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024042313282  COMPLETE              20.14
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             105.67
```
Approving now.

**Comment by MichaelLueken** [comment]
The Jet pipeline is down, so I manually ran the coverage WE2E tests on that machine.  All tests successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20240423141813                                           COMPLETE              17.34
custom_ESGgrid_20240423141816                                      COMPLETE              25.83
custom_ESGgrid_Great_Lakes_snow_8km_20240423141817                 COMPLETE              20.34
custom_GFDLgrid_20240423141819                                     COMPLETE              10.57
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018_202404  COMPLETE               8.76
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h_20  COMPLETE              80.60
get_from_HPSS_ics_RAP_lbcs_RAP_20240423141823                      COMPLETE              16.85
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20240423141824  COMPLETE             609.82
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              63.86
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               7.73
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_2024  COMPLETE             915.93
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1777.63
```

**Comment by MichaelLueken** [comment]
Several tests failed on Orion due to bad nodes.  Manual runs of the coverage WE2E tests on Orion have successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
custom_ESGgrid_SF_1p1km_20240423101846                             COMPLETE             425.35
deactivate_tasks_20240423101847                                    COMPLETE               1.06
get_from_AWS_ics_GEFS_lbcs_GEFS_fmt_grib2_2022040400_ensemble_2me  COMPLETE            1861.87
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_  COMPLETE             968.22
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20240  COMPLETE             370.59
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta_202404231  COMPLETE              20.08
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20240423101  COMPLETE             906.50
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_  COMPLETE              61.22
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_2  COMPLETE             728.08
grid_SUBCONUS_Ind_3km_ics_FV3GFS_lbcs_FV3GFS_suite_WoFS_v0_202404  COMPLETE              54.34
2020_CAD_20240423101857                                            COMPLETE              67.17
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            5464.48
```
Additionally, the automated tests on Derecho, Hera Intel, and Hercules have successfully passed.  Once the last tests on Gaea and Hera GNU have passed, I will be able to merge this PR.

**Comment by MichaelLueken** [comment]
The Gaea tests have successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20240423121827                                           COMPLETE              48.41
custom_ESGgrid_NewZealand_3km_20240423121838                       COMPLETE             100.11
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              45.78
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RAP_20240423121  COMPLETE              53.94
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024042312  COMPLETE              52.80
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson  COMPLETE             594.80
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024042  COMPLETE              41.15
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_20  COMPLETE             811.92
grid_SUBCONUS_Ind_3km_ics_RAP_lbcs_RAP_suite_RRFS_v1beta_plot_202  COMPLETE              21.22
2020_CAPE_20240423121928                                           COMPLETE              55.79
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1825.92
```
Merging this PR now.

**Pull request merged**
