### PR TITLE
[develop] Update UFS-WM hash to 11/14 version and UPP hash to 09/30 version.

### PR DESCRIPTION
**Pull request by MichaelLueken**
## DESCRIPTION OF CHANGES: 
- Update ufs-weather-model hash to [6b0f516](https://github.com/ufs-community/ufs-weather-model/commit/6b0f516557811eac82c17b852efb82a35892b022) (November 14, 2024)
- Update UPP hash to [6f5dd62](https://github.com/NOAA-EMC/UPP/commit/6f5dd627d124ae94bb5ed7f5afd22f82c470b1b7) (September 30, 2024)
- Use the `fms-2024.01` spack stack environment (replacing `upp-addon-env`) for Tier-1 platform modulefiles
- Replace `fms/2023.04` with `fms/2024.01` in `modulefiles/srw_common.lua`
- Removed `PRMSL` from `parm/metplus/STATAnalysisConfig_skill_score` in order to calculate the skill-score (`PRMSL` was replaced with `MSLET` in the `postxconfig-NT-fv3lam.txt` file)
- The `grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot` WE2E test was requiring over 6 hours in the `run_fcst` task to complete while using GNU executables.  Running with a single thread (`OMP_NUM_THREADS_RUN_FCST: 1`) allows the test to run using both GNU and Intel compilers without issue.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
- [x] derecho.intel - Fundamental, Comprehensive, and Fire sample config (`ush/config.fire.yaml`) tests were run
- [x] gaea.intel - Fundamental and Comprehensive tests were run
- [x] hera.gnu - Fundamental and Comprehensive tests were run
- [x] hera.intel - Fundamental, Comprehensive, AQM WE2E, and AQM sample config (`ush/config.aqm.yaml`) tests were run
- [x] hercules.intel - Fundamental, Comprehensive, AQM WE2E, and AQM sample config (`ush/config.aqm.yaml`) tests were run
- [x] jet.intel - Fundamental, Comprehensive, and Fire WE2E tests were run
- [x] orion.intel - Fundamental, Comprehensive, AQM WE2E, and AQM sample config (`ush/config.aqm.yaml`) tests were run
- [x] fundamental test suite
- [x] comprehensive tests (specify *which* if a subset was used)

## DOCUMENTATION:
No modifications are required in the documentation

## CHECKLIST
- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]
Approved.
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE              13.08
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE              10.17
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              27.43
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024112  COMPLETE              44.95
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241122183  COMPLETE              25.24
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024112218313  COMPLETE              48.41
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             169.28
```

**Review by rickgrubin-noaa — APPROVED** [review]
Approved per checklist and test results.

**Comment by MichaelLueken** [comment]
The automated Jenkins tests successfully passed on Derecho, Gaea, Hera Intel, Hercules, and Orion.

One test failed on each of Hera GNU and Jet.

On Hera GNU, the `vx-det_long-fcst_winter-wx_SRW-staged` WE2E test failed due to hitting the wallclock limit pulling `NOHRSC` data from HPSS.  On Jet, the `custom_ESGgrid_Great_Lakes_snow_8km` WE2E test failed due to hitting the wallclock limit pulling `NOHRSC` data from HPSS.

Both `rocotorewind` and `rocotoboot` were used to kick off these failed tests and they have successfully pulled the `NOHRSC` data from HPSS.  Once these two tests finish running, the updated logs will be posted, then this PR will get merged.

**Comment by MichaelLueken** [comment]
The Hera GNU WE2E tests have successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
custom_ESGgrid_Central_Asia_3km_20241122230202                     COMPLETE             318.97
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200_202411  COMPLETE              17.06
get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS_20241122230203              COMPLETE              24.10
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_2024112223  COMPLETE             448.19
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_202  COMPLETE              34.27
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20241122230  COMPLETE              34.56
long_fcst_20241122230206                                           COMPLETE             418.80
MET_verification_only_vx_20241122230207                            COMPLETE               0.36
MET_ensemble_verification_only_vx_time_lag_20241122230209          COMPLETE              13.19
2019_halloween_storm_20241122230214                                COMPLETE             617.80
2020_jan_cold_blast_20241122230215                                 COMPLETE             604.11
vx-det_long-fcst_custom-vx-config_aiml-fourcastnet_20241122230215  COMPLETE               0.77
vx-det_long-fcst_custom-vx-config_aiml-panguweather_2024112223021  COMPLETE               0.77
vx-det_long-fcst_custom-vx-config_gfs_20241122230219               COMPLETE               0.78
vx-det_long-fcst_winter-wx_SRW-staged_20241122230221               COMPLETE               1.25
vx-det_multicyc_fcst-overlap_ncep-hrrr_20241122230222              COMPLETE               7.37
vx-det_multicyc_last-obs-00z_ncep-hrrr_20241122230224              COMPLETE               1.44
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            2543.79
```
as well as the Jet WE2E tests:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
2019_hurricane_barry_20241122231213                                COMPLETE              83.04
community_20241122231216                                           COMPLETE              24.10
custom_ESGgrid_20241122231217                                      COMPLETE              39.48
custom_ESGgrid_Great_Lakes_snow_8km_20241122231218                 COMPLETE              29.96
custom_GFDLgrid_20241122231220                                     COMPLETE              14.87
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018_202411  COMPLETE              13.46
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h_20  COMPLETE             102.72
get_from_HPSS_ics_RAP_lbcs_RAP_20241122231223                      COMPLETE              20.59
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20241122231224  COMPLETE             528.87
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              96.90
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20241  COMPLETE               8.98
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             962.97
```
Moving forward with merging this PR now.

**Pull request merged**
