### PR TITLE
[develop] Fix sample script and WE2E test for AQM

### LINKED ISSUE #1019: [SRW-AQM] AQM sample script 'config.aqm.community.yaml' fails due to missing data files
## Expected behavior

The provided sample script for SRW-AQM is completed successfully.

## Current behavior

The `fire_emission` task fails due to missing data files:
```
202302170000           fire_emission                    55687737                DEAD                   1         2          18.0
```
```
+ print_msg.sh[275]: err_msg='\nFire Emission RAW data does not exist:
  FILE_13km_md1 = "Hourly_Emissions_13km_202302152300_202302152300.nc"
  DCOMINfire = "/scratch2/NCEPDEV/naqfc/RRFS_CMAQ/RAVE_fire"'
+ print_msg.sh[278]: printf 'FATAL ERROR:
```

## Machines affected

Hera

## Steps To Reproduce
1. Run the sample script `config.aqmcommunity.yaml`.

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 

- Fixes the failure on the sample script `ush/config.aqm.community.yaml`.
- Fixes the failure on the WE2E test `test/WE2E/test_configs/aqm/config.aqm_grid_AQM_NA13km_suite_GFS_v16.yaml` for AQM.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- Sample script run: `config.aqm.community.yaml`
- WE2E test: `config.aqm_grid_AQWM_NA13km_suite_GFS_v16.yaml`

- [x] hera.intel
- [ ] orion.intel
- [ ] hercules.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] derecho.intel
- [ ] gaea.intel
- [ ] gaeac5.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [x] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## ISSUE: 
Fixes issue mentioned in #1019 

## CHECKLIST

- [x] My code follows the style guidelines in the Contributor's Guide
- [x] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes do not require updates to the documentation (explain).
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## CONTRIBUTORS: 

@MichaelLueken @RatkoVasic-NOAA

### CODE REVIEW

**Comment by MichaelLueken** [comment]
@chan-hoo, Thank you very much for running the updated `config.aqm.community.yaml` sample script and `config.aqm_grid_AQWM_NA13km_suite_GFS_v16.yaml` WE2E test!

Please run the fundamental test suite on one of the machines as well, to ensure that these changes don't adversely affect the fundamental test suite.

In the `tests/WE2E` directory, using:

`./run_WE2E_tests.py -t fundamental -m <machine> -a <account>`

will allow you to run the fundamental test suite on a given machine.  Since you are still onboarding to EPIC, please let me know and I can run the fundamental test suite on a machine for you.

Thanks

**Comment by chan-hoo** [comment]
@MichaelLueken, the fundamental test has been completed successfully on Hera:
```
All 7 experiments finished
Calculating core-hour usage and printing final summary
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE               8.80
nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_timeoffset_suite_  COMPLETE              11.89
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               6.99
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              13.70
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024022  COMPLETE              26.67
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240220160  COMPLETE              13.61
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024022016095  COMPLETE              19.35
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             101.01
```

**Comment by MichaelLueken** [comment]
@chan-hoo, thank you very much for running the fundamental tests on Hera!  Once my AQM testing is complete, I will provide an approval for this work.

**Review by MichaelLueken — APPROVED** [review]
@chan-hoo, my AQM WE2E test has finally finished on Hera and the test has successfully passed.  These changes are similar to the changes that I have applied to update the test to the new 202311100000 - 202311110000 dates for the WE2E test.

Everything looks good, approving now!

```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
aqm_grid_AQM_NA13km_suite_GFS_v16_20240220144109                   COMPLETE            2686.93
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            2686.93
```

**Review by RatkoVasic-NOAA — APPROVED** [review]
Tested on Hera:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE               8.84
nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_timeoffset_suite_  COMPLETE              12.47
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               7.48
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              12.73
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024022  COMPLETE              26.66
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240228171  COMPLETE              13.53
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024022817165  COMPLETE              19.42
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             101.13

Detailed summary written to /scratch2/NCEPDEV/fv3-cam/Ratko.Vasic/1040/expt_dirs/WE2E_summary_20240228190343.txt

```
Approved.

**Comment by chan-hoo** [comment]
@RatkoVasic-NOAA, thank you very much for reviewing this PR!!! :)

**Comment by MichaelLueken** [comment]
The Jenkins tests have passed for Derecho, Hercules, Jet, and Orion.  There were issues for both Hera Intel and Hera GNU.  A rerun on Hera allowed the Hera Intel tests to pass, but the `get_from_NOMADS_ics_FV3GFS_lbcs_FV3GFS` test failed in Hera GNU.  Attempting to rerun the one failed test now.

Once it passes, I will merge this PR.

**Pull request merged**
