### PR TITLE
[develop] Update ufs-weather-model hash and further clean the machines tested in PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by MichaelLueken**
## DESCRIPTION OF CHANGES: 
* Update `ufs-weather-model` hash to [b5a1976](https://github.com/ufs-community/ufs-weather-model/commit/b5a1976012b66352f403588f95e639c6827b97d4) (July 30)
* Add `hera.gnu`, remove `cheyenne.intel`, `cheyenne.gnu`, and `gaeac5.intel`, and alphabetize the machines in the `TESTS CONDUCTED` section of the `PULL_REQUEST_TEMPLATE`
* Correct behavior of Jenkins `Functional WorkflowTaskTests`.  Currently, `TASK_DEPTH` is set to null, resulting in no tests being run during the `Functional WorkflowTaskTests` stage.  Replaced `env` with `params` in `Jenkinsfile` for setting `TASK_DEPTH`.  Testing shows that this will correctly set `TASK_DEPTH` to the default value of 9 and allow the tests to run.
* Removed extraneous entries from the verification scripts to remove `KeyError` messages in the associated verification log files.

### Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## TESTS CONDUCTED: 
- [X] derecho.intel - Fundamental tests and AQM sample config (`ush/config.aqm.yaml`) were run
- [X] gaea.intel - Fundamental and Comprehensive tests were run
- [X] hera.gnu - Fundamental tests were run
- [X] hera.intel - Fundamental and AQM WE2E tests were run
- [X] hercules.intel - Fundamental and AQM WE2E tests were run
- [X] jet.intel - Fundamental tests were run
- [X] orion.intel - Fundamental and AQM sample config (`ush/config.aqm.yaml`) were run
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [X] fundamental test suite
- [X] comprehensive tests

## CHECKLIST
- [X] My code follows the style guidelines in the Contributor's Guide
- [X] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by MichaelLueken** [comment]
@gspetro-NOAA -

I have updated the `doc/ContribGuide/contributing.rst` file to mirror the changes that I made to the `PULL_REQUEST_TEMPLATE`.

**Comment by EdwardSnyder-NOAA** [comment]
The fundamental test passed on AWS:
```
Calculating core-hour usage and printing final summary
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used
----------------------------------------------------------------------------------------------------
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta_2  COMPLETE             144.29
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE              22.37
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v17_p8_plot  COMPLETE              89.85
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR_2024080  COMPLETE             308.78
grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0_20240808185  COMPLETE              91.16
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GFS_v16_2024080818583  COMPLETE             134.93
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE             791.38

Detailed summary written to /contrib/Edward.Snyder/pr-1096/expt_dirs/WE2E_summary_20240808214549.txt
```
In order to pass the plot we2e on AWS I had to update the `modulefiles/tasks/noaacloud/plot_allvars.local.lua` file to this:
```
load("conda")
setenv("SRW_GRAPHICS_ENV", "srw_graphics")
```

I thought I included this change in my [PR-1091](https://github.com/ufs-community/ufs-srweather-app/pull/1091) that addressed PW build issues. Would it be possible to include updating the plotting lua file in this PR or do we need to make a new PR for this change?

**Comment by MichaelLueken** [comment]
@EdwardSnyder-NOAA -

Thanks for bringing this to my attention!  I will go ahead and add this modification to the `modulefiles/tasks/noaacloud/plot_allvars.local.lua` file in this PR, I don't see a reason to create a completely different PR for this.

**Comment by MichaelLueken** [comment]
@EdwardSnyder-NOAA -

I have updated the `modulefiles/tasks/noaacloud/plot_allvars.local.lua` file.  Please let me know if I need to make any other modifications.  Thanks!

**Comment by EdwardSnyder-NOAA** [comment]
Changes look good! Thanks for including it. Approving.

**Review by EdwardSnyder-NOAA — APPROVED** [review]

**Comment by MichaelLueken** [comment]
All Jenkins tests successfully passed, with the exception of Jet, which were aborted for taking longer than 8 hours to complete.

The coverage WE2E tests were manually ran on Jet and all successfully passed:
```
----------------------------------------------------------------------------------------------------
Experiment name                                                  | Status    | Core hours used 
----------------------------------------------------------------------------------------------------
community_20240809205623                                           COMPLETE              24.31
custom_ESGgrid_20240809205625                                      COMPLETE              32.17
custom_ESGgrid_Great_Lakes_snow_8km_20240809205625                 COMPLETE              26.79
custom_GFDLgrid_20240809205627                                     COMPLETE              16.28
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021032018_202408  COMPLETE              13.18
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2022060112_48h_20  COMPLETE             100.43
get_from_HPSS_ics_RAP_lbcs_RAP_20240809205630                      COMPLETE              20.14
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR_20240809205632  COMPLETE             639.58
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16_plot_20  COMPLETE              73.89
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2_20240  COMPLETE               9.91
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta_2024  COMPLETE             974.37
----------------------------------------------------------------------------------------------------
Total                                                              COMPLETE            1931.05
```
Moving forward with merging this PR now.

**Pull request merged**
