### PR TITLE
[develop] Bugfix find task function in setup.py

### PR DESCRIPTION
**Pull request by danielabdi-noaa**
## DESCRIPTION OF CHANGES: 

There seems to be a bug in `dict_find`. I am not sure how it worked so far.
- When a task is found but is deeper in the dictionary it returns `False`
- In some cases it returns `None` instead of `False`
- Logic for `task_make_lbcs` is wrong

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [ ] hera.intel
- [ ] orion.intel
- [ ] cheyenne.intel
- [ ] cheyenne.gnu
- [ ] gaea.intel
- [ ] jet.intel
- [ ] wcoss2.intel
- [ ] NOAA Cloud (indicate which platform)
- [ ] Jenkins
- [ ] fundamental test suite
- [ ] comprehensive tests (specify *which* if a subset was used)

## CHECKLIST

- [ ] My code follows the style guidelines in the Contributor's Guide
- [ ] I have performed a self-review of my own code using the Code Reviewer's Guide
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## LABELS (optional): 

A Code Manager needs to add the following labels to this PR: 
- [ ] Work In Progress
- [ ] bug
- [ ] enhancement
- [ ] documentation
- [ ] release
- [ ] high priority
- [ ] run_ci
- [ ] run_we2e_fundamental_tests
- [ ] run_we2e_comprehensive_tests
- [ ] Needs Cheyenne test 
- [ ] Needs Jet test 
- [ ] Needs Hera test 
- [ ] Needs Orion test 
- [ ] help wanted

### CODE REVIEW

**Review by MichaelLueken — APPROVED** [review]
@danielabdi-noaa These changes look good to me!  Thanks for correcting `run_make_lbcs` - renaming `task_make_ics` to `task_make_lbcs`.

**Review by chan-hoo — APPROVED** [review]

**Comment by MichaelLueken** [comment]
@danielabdi-noaa As of this time, there is the expected failure of the `grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR` test on Hera Intel (due to issue #688).

I'm also noting a failure on Cheyenne GNU, the `nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km` test.  This test is failing in the post.  Unfortunately, there is no error message in the post log files.  It prints:

`Starting post-processing for fhr = 000 hr...`

and then stops.  If you would like to look at the output, please see:

`/glade/scratch/epicufsrt/jenkins/workspace/fs-srweather-app_pipeline_PR-745/expt_dirs/nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km`

I'll try manually running this test and see if it passes or fails.  I'll let you know what I find.

**Comment by MichaelLueken** [comment]
@danielabdi-noaa Following up, manual reruns of the `nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km` test are failing as well.  I am seeing the following in the log files for the post in these runs:

```
Launching J-job (jjob_fp) for task "run_post" ...
  jjob_fp = "/glade/scratch/mlueken/ufs-srweather-app/jobs/JREGIONAL_RUN_POST"

/glade/scratch/mlueken/ufs-srweather-app/ush/job_preamble.sh: line 22: [: -eq: unary operator expected

"ln_vrfy" operation returned with a message.  This command was
issued from the script in file:

  ""

Message from "ln_vrfy" function's "ln" operation:
  ln: target '/glade/scratch/mlueken/ufs-srweather-app/expt_dirs/nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km/log/make_lbcs_mem000_2019061500.log' is not a directory
```
I'm also seeing:

```
Starting post-processing for fhr = 002 hr...
/glade/scratch/mlueken/ufs-srweather-app/ush/bash_utils/print_msg.sh: line 192: BASH_SOURCE[1]: unbound variable
FATAL ERROR:
ERROR:
  From script:  ""
  Full path to script:  ""
Call to executable to run post for forecast hour 002 returned with non-
zero exit code.
Exiting with nonzero status.
FATAL ERROR:
ERROR:
  From script:  "JREGIONAL_RUN_POST"
  Full path to script:  "/glade/scratch/mlueken/ufs-srweather-app/jobs/JREGIONAL_RUN_POST"
Call to ex-script corresponding to J-job "JREGIONAL_RUN_POST" failed.
Exiting with nonzero status.

```
I'll try running the test separately on another platform to see if it is an issue only on Cheyenne or if it is also present on other machines.

I'm trying to see now if this is an issue with the test itself, or if this is an issue associated with issue #652.  I'll continue trying to see if I can't uncover any other issues with this test.

**Comment by MichaelLueken** [comment]
The `nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km` test successfully completed on Hera.  I'll retry running the test on Cheyenne Monday morning, but the fact that the test passes on other machines makes the failure seem like what is documented in issue #652.

**Review by christinaholtNOAA — APPROVED** [review]
LGTM.

**Comment by MichaelLueken** [comment]
The rerun of the `nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km` on Cheyenne this morning once again failed for some of the `run_post` tasks.  This is likely due to issue #652, so I will move forward with merging this work now.

**Pull request merged**
