### PR TITLE
Update srw_common and hashes of UFS_UTILS and UPP 

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
- The hashes of UFS_UTILS and UPP are updated with the latest ones.
- the module file `srw_comm` is updated with the latest modules.
- Since the latest hash of the ufs weather model requires changes in the input namelists, it will be updated in a separate PR later. However, I confirmed that the latest hash of the ufs weather model was built successfully with `srw_common` in this PR on Orion and Hera.

## TESTS CONDUCTED: 
- successfully built on Orion and Hera.
- WE2E tests on Orion and Hera:
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha

## DEPENDENCIES:
- ufs-community/regional_workflow/pull/775

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by mkavulich** [comment]
Testing on Cheyenne, not sure if all the new modules will be available yet.

**Comment by mkavulich** [comment]
Build tests did indeed fail on Cheyenne. I believe this PR will need to incorporate some of Ed's PR (https://github.com/ufs-community/ufs-srweather-app/pull/250), but all the library combinations I tried failed in some way. I also opened an issue in the hpc-stack repository a while back (https://github.com/NOAA-EMC/hpc-stack/issues/439) but it has not yet received a satisfactory resolution.

**Comment by chan-hoo** [comment]
@mkavulich, thank you for testing it on Cheyenne. Do you think this PR should be on hold until the modules are ready on Cheyenne or closed?

**Comment by JeffBeck-NOAA** [comment]
Hi @chan-hoo, I just tested on Jet and after invoking "devbuild.sh -p=jet", I get:

```
... Load MODULE_FILE and create BUILD directory ...
Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as
requested: "nccmp/1.8.9.0"
   Try: "module spider nccmp/1.8.9.0" to see how to load the module(s).

Executing this command requires loading "nccmp/1.8.9.0" which failed while processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    srw_common       /mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/modulefiles/srw_common
    build_jet_intel  /mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/modulefiles/build_jet_intel
```

Looks like nccmp/1.8.9.0 is not available system-wide yet:

```
-------------------------------------------------------------------------------------------------------------
  nccmp:
-------------------------------------------------------------------------------------------------------------
     Versions:
        nccmp/1.8.2.1
        nccmp/1.8.5
```
I see that UFS_UTILS calls for 1.8.9.0 in UFS_UTILS/modulesfiles/build.jet.intel.lua; however, this is how it's done:
```
nccmp_ver=os.getenv("nccmp_ver") or "1.8.9.0"
load(pathJoin("nccmp", nccmp_ver))
```

Earlier in that module file, there's the equivalent of a "module use" command for the following:

`prepend_path("MODULEPATH", "/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack")`

That appears to be where nccmp/1.8.9.0 exists:

```
[jet|fe1]/mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/src/UFS_UTILS/modulefiles((HEAD detached at b6efa865))> module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack
[jet|fe1]/mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/src/UFS_UTILS/modulefiles((HEAD detached at b6efa865))> module load nccmp/1.8.9.0
[jet|fe1]/mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/src/UFS_UTILS/modulefiles((HEAD detached at b6efa865))> module list

Currently Loaded Modules:
  1) hdf5/1.10.6   2) netcdf/4.7.4   3) nccmp/1.8.9.0
```

Do we need to move "nccmp" out of srw_common and load it manually in each build file?  I'm not sure how else to load it, since the "module use" command is specific to Jet and can't go in srw_common.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @chan-hoo for fixing the problem with nccmp on Jet.  I'm now getting the following error when building UFS_UTILS.

```
CMake Error at tests/CMakeLists.txt:21 (message):
  Could not download gfs.v16.sfc.history.nc
Call Stack (most recent call first):
  tests/chgres_cube/CMakeLists.txt:16 (PULL_DATA)

-- Configuring incomplete, errors occurred!
See also "/mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/build/src/UFS_UTILS/src/UFS_UTILS-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [src/UFS_UTILS/src/UFS_UTILS-stamp/UFS_UTILS-configure] Error 1
make[1]: *** [src/CMakeFiles/UFS_UTILS.dir/all] Error 2
```

In UFS_UTILS/tests/chgres_cube/CMakeLists.txt, I see this:

```
# This function is used to download unit test data.
# It takes two arguments, the URL and the file to
# be downloaded.

function(PULL_DATA THE_URL THE_FILE)
  if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/data/${THE_FILE}")
    file(DOWNLOAD
      ${THE_URL}/${THE_FILE}
      ${CMAKE_CURRENT_BINARY_DIR}/data/${THE_FILE}
      SHOW_PROGRESS
      STATUS status
      INACTIVITY_TIMEOUT 30
      )
    list(GET status 0 status_num)
    if(NOT status_num EQUAL 0 OR NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/data/${THE_FILE}")
      message(FATAL_ERROR "Could not download ${THE_FILE}")
```
@GeorgeGayno-NOAA, any idea why the download of gfs.v16.sfc.history.nc would fail on Jet?

**Comment by GeorgeGayno-NOAA** [comment]
> Thanks, @chan-hoo for fixing the problem with nccmp on Jet. I'm now getting the following error when building UFS_UTILS.
> 
> ```
> CMake Error at tests/CMakeLists.txt:21 (message):
>   Could not download gfs.v16.sfc.history.nc
> Call Stack (most recent call first):
>   tests/chgres_cube/CMakeLists.txt:16 (PULL_DATA)
> 
> -- Configuring incomplete, errors occurred!
> See also "/mnt/lfs4/BMC/wrfruc/beck/ufs-srweather-app/build/src/UFS_UTILS/src/UFS_UTILS-build/CMakeFiles/CMakeOutput.log".
> make[2]: *** [src/UFS_UTILS/src/UFS_UTILS-stamp/UFS_UTILS-configure] Error 1
> make[1]: *** [src/CMakeFiles/UFS_UTILS.dir/all] Error 2
> ```
> 
> In UFS_UTILS/tests/chgres_cube/CMakeLists.txt, I see this:
> 
> ```
> # This function is used to download unit test data.
> # It takes two arguments, the URL and the file to
> # be downloaded.
> 
> function(PULL_DATA THE_URL THE_FILE)
>   if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/data/${THE_FILE}")
>     file(DOWNLOAD
>       ${THE_URL}/${THE_FILE}
>       ${CMAKE_CURRENT_BINARY_DIR}/data/${THE_FILE}
>       SHOW_PROGRESS
>       STATUS status
>       INACTIVITY_TIMEOUT 30
>       )
>     list(GET status 0 status_num)
>     if(NOT status_num EQUAL 0 OR NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/data/${THE_FILE}")
>       message(FATAL_ERROR "Could not download ${THE_FILE}")
> ```
> 
> @GeorgeGayno-NOAA, any idea why the download of gfs.v16.sfc.history.nc would fail on Jet?

The download of unit test data was made part of UFS_UTILS build system a few month's ago. See https://github.com/ufs-community/UFS_UTILS/issues/619 for more details. Jet is behind a firewall and can't access the EMC ftp site. So to build on that machine you must set this CMake flag as follows: `-DBUILD_TESTING=OFF`. If you need to build and run the unit tests locally, you will need to use Hera or Orion.

**Comment by chan-hoo** [comment]
@GeorgeGayno-NOAA, thank you for this info. @JeffBeck-NOAA, I'll add the flag to devbuild.sh soon.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @GeorgeGayno-NOAA!  @chan-hoo, I'll test again as soon as devbuild.sh is updated.  Thanks!

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, I changed 'src/CMakeLists.txt' directly because we don't need the unit test for UFS_UTILS in UFS SRW App. Can you test it again?

**Comment by mkavulich** [comment]
@chan-hoo I am tagging @mark-a-potts and @EdwardSnyder-NOAA RE: Cheyenne build problems. I am out of the loop on the status of the new library builds on Cheyenne.

**Comment by mark-a-potts** [comment]
Do all the new modules exist on the Tier-1 platforms? EPIC can install any that are missing on Cheyenne, but we don't currently control the installation on the other machines.

**Comment by chan-hoo** [comment]
@mark-a-potts, I've tested it on Hera and Orion successfully, and I think @JeffBeck-NOAA is testing it on Jet. WCOSS will be away in June, so we don't need to worry about wcoss_dell_p3. I don't have access to other machines. I updated the modules for Cheyenne and other machines on the basis of `ufs_common` in the ufs-weather-model. Can you test it on Cheyenne?

**Comment by JeffBeck-NOAA** [comment]
@chan-hoo, the build on Jet now completes successfully.  I was able to get the GST to run with the following changes (similar to what we had to do on Hera recently):

In ufs-srweather-app/modulefiles/wflow_jet (change top to bottom)

```
module use -a /contrib/miniconda3/modulefiles
module load miniconda3

module use /contrib/miniconda3/modulefiles
module load miniconda3/4.5.12
```

In regional_workflow/modulefiles/tasks/jet/miniconda_regional_workflow (change top to bottom):

```
module use -a /contrib/miniconda3/modulefiles
module load miniconda3

module use /contrib/miniconda3/modulefiles
module load miniconda3/4.5.12
```

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, thank you for testing it. I've updated the scripts for Jet.

**Comment by jkbk2004** [comment]
@mkavulich @chan-hoo on cheyenne, ufs-wm currently uses: module use /glade/work/epicufsrt/GMTB/tools/intel/2022.1/hpc-stack-v1.2.0_6eb6/modulefiles/stack and /glade/work/epicufsrt/GMTB/tools/gnu/10.1.0/hpc-stack-v1.2.0/modulefiles/stack

**Comment by chan-hoo** [comment]
@jkbk2004, as you can see, this PR updates the paths to the hpc-stack on Cheyenne with the ones you pointed above. Can you test this PR on Cheyenne?

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
